export const subscription = {
  id: "subscription_1",
  created_at: "2026-01-01T00:00:00Z",
  modified_at: null,
  amount: 1_000,
  currency: "usd",
  recurring_interval: "month",
  recurring_interval_count: 1,
  status: "paused",
  units: null,
  current_period_start: "2026-01-01T00:00:00Z",
  current_period_end: "2026-02-01T00:00:00Z",
  current_meter_period_start: null,
  current_meter_period_end: null,
  trial_start: null,
  trial_end: null,
  cancel_at_period_end: false,
  canceled_at: null,
  started_at: "2026-01-01T00:00:00Z",
  ends_at: null,
  ended_at: null,
  pause_at_period_end: false,
  paused_at: "2026-01-10T00:00:00Z",
  resumes_at: null,
  customer_id: "customer_1",
  product_id: "product_1",
  discount_id: null,
  checkout_id: "checkout_1",
  customer_cancellation_reason: null,
  customer_cancellation_comment: null,
  metadata: {},
};

export const order = {
  id: "order_1",
  created_at: "2026-01-01T00:00:00Z",
  modified_at: null,
  status: "paid",
  units: null,
  paid: true,
  subtotal_amount: 1_000,
  discount_amount: 0,
  net_amount: 1_000,
  tax_amount: 0,
  total_amount: 1_000,
  applied_balance_amount: 0,
  due_amount: 0,
  refunded_amount: 0,
  refunded_tax_amount: 0,
  refundable_amount: 1_000,
  refundable_tax_amount: 0,
  currency: "usd",
  billing_reason: "subscription_cycle",
  billing_name: null,
  billing_address: null,
  invoice_number: "INV-1",
  receipt_number: null,
  is_invoice_generated: true,
  customer_id: "customer_1",
  product_id: "product_1",
  discount_id: null,
  subscription_id: "subscription_1",
  checkout_id: null,
  description: "Pro Monthly",
  platform_fee_amount: 0,
  platform_fee_currency: null,
  metadata: {},
  items: [],
};

export const refund = {
  id: "refund_1",
  created_at: "2026-02-01T00:00:00Z",
  modified_at: null,
  metadata: {},
  status: "succeeded",
  reason: "customer_request",
  amount: 300,
  tax_amount: 0,
  currency: "usd",
  organization_id: "organization_1",
  order_id: "order_1",
  subscription_id: null,
  customer_id: "customer_1",
  revoke_benefits: false,
  dispute: null,
};

export const product = {
  id: "product_1",
  created_at: "2026-01-01T00:00:00Z",
  modified_at: null,
  trial_interval: null,
  trial_interval_count: null,
  name: "Pro Monthly",
  description: null,
  visibility: "public",
  recurring_interval: "month",
  recurring_interval_count: 1,
  meter_interval: null,
  meter_interval_count: null,
  is_recurring: true,
  is_archived: false,
  organization_id: "organization_1",
  metadata: {},
  is_deletable: true,
  prices: [
    {
      id: "price_1",
      created_at: "2026-01-01T00:00:00Z",
      modified_at: null,
      source: "catalog",
      amount_type: "fixed",
      price_currency: "usd",
      tax_behavior: null,
      is_archived: false,
      product_id: "product_1",
      price_amount: 2_000,
    },
  ],
  benefits: [],
  medias: [],
  attached_custom_fields: [],
};

export const discount = {
  id: "discount_1",
  created_at: "2026-01-01T00:00:00Z",
  modified_at: null,
  metadata: {},
  name: "Launch 20%",
  code: "LAUNCH20",
  type: "percentage",
  duration: "repeating",
  duration_in_months: 3,
  basis_points: 2_000,
  starts_at: null,
  ends_at: null,
  max_redemptions: null,
  max_redemptions_per_customer: null,
  redemptions_count: 1,
  organization_id: "organization_1",
  products: [],
};
