service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]
  telemetry:
    resource:
      service.name: jaeger
    logs:
      level: warn

extensions:
  healthcheckv2:
    use_v2: true
    http:

  jaeger_query:
    storage:
      traces: main
      traces_archive: archive

  jaeger_storage:
    backends:
      main:
        badger:
          directories:
            keys: /badger/main
            values: /badger/main
          ephemeral: false
          ttl:
            spans: 168h # 7 days
      archive:
        badger:
          directories:
            keys: /badger/archive
            values: /badger/archive
          ephemeral: false
          ttl:
            spans: 720h # 30 days

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: main
