import * as Schema from "effect/Schema";

import { RefundWebhookPayloadSchema } from "../refunds/webhook";
import {
  RestAddressSchema,
  RestAttributeSchema,
  RestDiscountAllocationSchema,
  RestMoneyBagSchema,
  RestTaxLineSchema,
  emptyText,
  fromRest,
  gid,
  normalizeAmount,
  splitTags,
  upper,
} from "../shared";
import {
  DiscountAllocationMethodSchema,
  type DiscountApplication,
  DiscountApplicationTypeSchema,
  DiscountTargetSelectionSchema,
  DiscountTargetTypeSchema,
  DiscountValueTypeSchema,
  OrderCancelReasonSchema,
  OrderFinancialStatusSchema,
  type OrderUpdate,
} from "./row";

const nullableMoney = Schema.optional(Schema.NullOr(RestMoneyBagSchema));

const RestShippingLineSchema = Schema.Struct({
  id: Schema.NullOr(Schema.Number),
  title: Schema.String,
  code: Schema.NullOr(Schema.String),
  source: Schema.NullOr(Schema.String),
  carrier_identifier: Schema.NullOr(Schema.String),
  phone: Schema.NullOr(Schema.String),
  is_removed: Schema.Boolean,
  price_set: RestMoneyBagSchema,
  discounted_price_set: RestMoneyBagSchema,
  current_discounted_price_set: RestMoneyBagSchema,
  tax_lines: Schema.Array(RestTaxLineSchema),
  discount_allocations: Schema.Array(RestDiscountAllocationSchema),
});

const RestLineItemSchema = Schema.Struct({
  admin_graphql_api_id: Schema.String,
  name: Schema.String,
  title: Schema.String,
  variant_title: Schema.NullOr(Schema.String),
  sku: Schema.NullOr(Schema.String),
  vendor: Schema.NullOr(Schema.String),
  product_id: Schema.NullOr(Schema.Number),
  variant_id: Schema.NullOr(Schema.Number),
  quantity: Schema.Int,
  current_quantity: Schema.Int,
  taxable: Schema.Boolean,
  requires_shipping: Schema.Boolean,
  gift_card: Schema.Boolean,
  price_set: RestMoneyBagSchema,
  total_discount_set: RestMoneyBagSchema,
  tax_lines: Schema.Array(RestTaxLineSchema),
  discount_allocations: Schema.Array(RestDiscountAllocationSchema),
  properties: Schema.Array(RestAttributeSchema),
});

const RestDiscountApplicationSchema = Schema.Struct({
  type: upper(DiscountApplicationTypeSchema),
  code: Schema.optional(Schema.NullOr(Schema.String)),
  title: Schema.optional(Schema.NullOr(Schema.String)),
  description: Schema.optional(Schema.NullOr(Schema.String)),
  allocation_method: upper(DiscountAllocationMethodSchema),
  target_selection: upper(DiscountTargetSelectionSchema),
  target_type: upper(DiscountTargetTypeSchema),
  value_type: upper(DiscountValueTypeSchema),
  value: Schema.String,
});

export const OrderWebhookPayloadSchema = Schema.Struct({
  id: Schema.Number,
  admin_graphql_api_id: Schema.String,
  name: Schema.String,
  // Protected fields can be missing without protected data access.
  email: Schema.optional(Schema.NullOr(Schema.String)),
  phone: Schema.optional(Schema.NullOr(Schema.String)),
  customer: Schema.optional(Schema.NullOr(Schema.Struct({ admin_graphql_api_id: Schema.String }))),
  customer_locale: Schema.NullOr(Schema.String),
  buyer_accepts_marketing: Schema.Boolean,
  billing_address: Schema.optional(Schema.NullOr(RestAddressSchema)),
  shipping_address: Schema.optional(Schema.NullOr(RestAddressSchema)),
  note: Schema.optional(Schema.NullOr(Schema.String)),
  note_attributes: Schema.Array(RestAttributeSchema),
  tags: Schema.String,
  confirmation_number: Schema.NullOr(Schema.String),
  po_number: Schema.NullOr(Schema.String),
  source_name: Schema.NullOr(Schema.String),
  source_identifier: Schema.NullOr(Schema.String),
  app_id: Schema.NullOr(Schema.Number),
  payment_gateway_names: Schema.Array(Schema.String),
  test: Schema.Boolean,
  taxes_included: Schema.Boolean,
  tax_exempt: Schema.Boolean,
  duties_included: Schema.Boolean,
  estimated_taxes: Schema.Boolean,
  total_weight: Schema.NullOr(Schema.Int),
  financial_status: Schema.NullOr(upper(OrderFinancialStatusSchema)),
  cancel_reason: Schema.NullOr(upper(OrderCancelReasonSchema)),
  cancelled_at: Schema.NullOr(Schema.DateFromString),
  closed_at: Schema.NullOr(Schema.DateFromString),
  processed_at: Schema.DateFromString,
  created_at: Schema.DateFromString,
  updated_at: Schema.DateFromString,
  currency: Schema.String,
  presentment_currency: Schema.String,
  discount_codes: Schema.Array(Schema.Struct({ code: Schema.String })),
  discount_applications: Schema.Array(RestDiscountApplicationSchema),
  subtotal_price_set: nullableMoney,
  current_subtotal_price_set: RestMoneyBagSchema,
  total_discounts_set: nullableMoney,
  current_total_discounts_set: RestMoneyBagSchema,
  total_shipping_price_set: RestMoneyBagSchema,
  current_shipping_price_set: RestMoneyBagSchema,
  total_tax_set: nullableMoney,
  current_total_tax_set: RestMoneyBagSchema,
  original_total_duties_set: nullableMoney,
  current_total_duties_set: nullableMoney,
  total_price_set: RestMoneyBagSchema,
  current_total_price_set: RestMoneyBagSchema,
  tax_lines: Schema.Array(RestTaxLineSchema),
  shipping_lines: Schema.Array(RestShippingLineSchema),
  line_items: Schema.Array(RestLineItemSchema),
  refunds: Schema.Array(RefundWebhookPayloadSchema),
});

export const OrderDeleteWebhookPayloadSchema = Schema.Struct({ id: Schema.Number });

export const OrderEventSchema = Schema.Union([
  Schema.Struct({
    _tag: Schema.Literal("upsert"),
    payload: Schema.toType(OrderWebhookPayloadSchema),
  }),
  Schema.Struct({
    _tag: Schema.Literal("delete"),
    id: Schema.String,
    version: Schema.Date,
  }),
]);

export type OrderWebhookPayload = Schema.Schema.Type<typeof OrderWebhookPayloadSchema>;

const orMoney = (bag: Schema.Schema.Type<typeof RestMoneyBagSchema> | null | undefined) =>
  bag === undefined || bag === null ? null : fromRest.money(bag);

export const fromOrderWebhook = (payload: OrderWebhookPayload): OrderUpdate => ({
  id: payload.admin_graphql_api_id,
  legacyResourceId: String(payload.id),
  name: payload.name,
  ...(payload.email === undefined ? {} : { email: emptyText(payload.email) }),
  ...(payload.phone === undefined ? {} : { phone: emptyText(payload.phone) }),
  ...(payload.customer === undefined
    ? {}
    : { customerId: payload.customer?.admin_graphql_api_id ?? "" }),
  customerLocale: emptyText(payload.customer_locale),
  customerAcceptsMarketing: payload.buyer_accepts_marketing,
  ...(payload.billing_address === undefined
    ? {}
    : { billingAddress: payload.billing_address && fromRest.address(payload.billing_address) }),
  ...(payload.shipping_address === undefined
    ? {}
    : { shippingAddress: payload.shipping_address && fromRest.address(payload.shipping_address) }),
  ...(payload.note === undefined ? {} : { note: emptyText(payload.note) }),
  customAttributes: payload.note_attributes.map(fromRest.attribute),
  tags: splitTags(payload.tags),
  confirmationNumber: emptyText(payload.confirmation_number),
  poNumber: emptyText(payload.po_number),
  sourceName: emptyText(payload.source_name),
  sourceIdentifier: emptyText(payload.source_identifier),
  appId: payload.app_id === null ? "" : gid("App", payload.app_id),
  paymentGatewayNames: payload.payment_gateway_names,
  test: payload.test,
  taxesIncluded: payload.taxes_included,
  taxExempt: payload.tax_exempt,
  dutiesIncluded: payload.duties_included,
  estimatedTaxes: payload.estimated_taxes,
  totalWeight: payload.total_weight,
  displayFinancialStatus: payload.financial_status,
  cancelReason: payload.cancel_reason,
  cancelledAt: payload.cancelled_at,
  closedAt: payload.closed_at,
  processedAt: payload.processed_at,
  createdAt: payload.created_at,
  updatedAt: payload.updated_at,
  currencyCode: payload.currency,
  presentmentCurrencyCode: payload.presentment_currency,
  discountCodes: payload.discount_codes.map((discount) => discount.code),
  discountApplications: payload.discount_applications.map(
    (application, index): DiscountApplication => ({
      index,
      type: application.type,
      code: application.type === "DISCOUNT_CODE" ? (application.code ?? null) : null,
      title: application.type === "DISCOUNT_CODE" ? null : (application.title ?? null),
      description: application.type === "MANUAL" ? (application.description ?? null) : null,
      allocationMethod: application.allocation_method,
      targetSelection: application.target_selection,
      targetType: application.target_type,
      valueType: application.value_type,
      value: normalizeAmount(application.value),
    }),
  ),
  subtotalPriceSet: orMoney(payload.subtotal_price_set),
  currentSubtotalPriceSet: fromRest.money(payload.current_subtotal_price_set),
  totalDiscountsSet: orMoney(payload.total_discounts_set),
  currentTotalDiscountsSet: fromRest.money(payload.current_total_discounts_set),
  totalShippingPriceSet: fromRest.money(payload.total_shipping_price_set),
  currentShippingPriceSet: fromRest.money(payload.current_shipping_price_set),
  totalTaxSet: orMoney(payload.total_tax_set),
  currentTotalTaxSet: fromRest.money(payload.current_total_tax_set),
  originalTotalDutiesSet: orMoney(payload.original_total_duties_set),
  currentTotalDutiesSet: orMoney(payload.current_total_duties_set),
  totalPriceSet: fromRest.money(payload.total_price_set),
  currentTotalPriceSet: fromRest.money(payload.current_total_price_set),
  taxLines: payload.tax_lines.map(fromRest.taxLine),
  shippingLines: payload.shipping_lines.map((line) => ({
    id: line.id === null ? null : gid("ShippingLine", line.id),
    title: line.title,
    code: line.code,
    source: line.source,
    carrierIdentifier: line.carrier_identifier,
    phone: line.phone,
    isRemoved: line.is_removed,
    originalPriceSet: fromRest.money(line.price_set),
    discountedPriceSet: fromRest.money(line.discounted_price_set),
    currentDiscountedPriceSet: fromRest.money(line.current_discounted_price_set),
    taxLines: line.tax_lines.map(fromRest.taxLine),
    discountAllocations: line.discount_allocations.map(fromRest.discountAllocation),
  })),
  lineItems: payload.line_items.map((item) => ({
    id: item.admin_graphql_api_id,
    name: item.name,
    title: item.title,
    variantTitle: item.variant_title,
    sku: item.sku,
    vendor: item.vendor,
    productId: item.product_id === null ? null : gid("Product", item.product_id),
    variantId: item.variant_id === null ? null : gid("ProductVariant", item.variant_id),
    quantity: item.quantity,
    currentQuantity: item.current_quantity,
    taxable: item.taxable,
    requiresShipping: item.requires_shipping,
    isGiftCard: item.gift_card,
    originalUnitPriceSet: fromRest.money(item.price_set),
    totalDiscountSet: fromRest.money(item.total_discount_set),
    taxLines: item.tax_lines.map(fromRest.taxLine),
    discountAllocations: item.discount_allocations.map(fromRest.discountAllocation),
    customAttributes: item.properties.map(fromRest.attribute),
  })),
});
