// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: wings/cluster.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { type CallContext, type CallOptions } from "nice-grpc-common";

import { Empty } from "../google/protobuf/empty.js";
import { FieldMask } from "../google/protobuf/field_mask.js";
import { Schema } from "../schema/arrow_type.js";
import { messageTypeRegistry } from "../typeRegistry.js";

export const protobufPackage = "wings.cluster";

export interface CreateNamespaceRequest {
  $type: "wings.cluster.CreateNamespaceRequest";
  /** The namespace id. */
  readonly namespaceId: string;
  /** The namespace definition. */
  readonly namespace: Namespace | undefined;
}

export interface UpdateNamespaceRequest {
  $type: "wings.cluster.UpdateNamespaceRequest";
  /**
   * The namespace to update.
   *
   * The namespace `name` field is used to identify the namespace to update.
   * Format: `namespaces/{namespace}`.
   */
  readonly namespace: Namespace | undefined;
  /** The list of fields to update. */
  readonly updateMask: readonly string[] | undefined;
}

export interface GetNamespaceRequest {
  $type: "wings.cluster.GetNamespaceRequest";
  /**
   * The namespace name.
   *
   * Format: `namespaces/{namespace}`
   */
  readonly name: string;
}

export interface ListNamespacesRequest {
  $type: "wings.cluster.ListNamespacesRequest";
  /**
   * The number of namespaces to return.
   *
   * Default: 100
   * Maximum: 1000
   */
  readonly pageSize?: number | undefined;
  /** The continuation token. */
  readonly pageToken?: string | undefined;
}

export interface ListNamespacesResponse {
  $type: "wings.cluster.ListNamespacesResponse";
  /** The namespaces. */
  readonly namespaces: readonly Namespace[];
  /** The continuation token. */
  readonly nextPageToken?: string | undefined;
}

export interface DeleteNamespaceRequest {
  $type: "wings.cluster.DeleteNamespaceRequest";
  /**
   * The namespace name.
   *
   * Format: `namespaces/{namespace}`
   */
  readonly name: string;
}

export interface Namespace {
  $type: "wings.cluster.Namespace";
  /**
   * The namespace name.
   *
   * Format: `namespaces/{namespace}`
   */
  readonly name: string;
  /** The object store configuration. */
  readonly objectStore: ObjectStore | undefined;
  /** The lake configuration. */
  readonly lake: Lake | undefined;
}

export interface ObjectStore {
  $type: "wings.cluster.ObjectStore";
  /** Object store configuration. */
  readonly objectStoreConfig?:
    | { readonly $case: "aws"; readonly aws: AwsConfiguration }
    | { readonly $case: "azure"; readonly azure: AzureConfiguration }
    | { readonly $case: "google"; readonly google: GoogleConfiguration }
    | { readonly $case: "s3Compatible"; readonly s3Compatible: S3CompatibleConfiguration }
    | undefined;
}

export interface CreateTableRequest {
  $type: "wings.cluster.CreateTableRequest";
  /**
   * The namespace that owns the table.
   *
   * Format: namespaces/{namespace}
   */
  readonly parent: string;
  /** The table id. */
  readonly tableId: string;
  /** The table metadata. */
  readonly table: Table | undefined;
}

export interface GetTableRequest {
  $type: "wings.cluster.GetTableRequest";
  /**
   * The table name.
   *
   * Format: namespaces/{namespace}/tables/{table}
   */
  readonly name: string;
}

export interface ListTablesRequest {
  $type: "wings.cluster.ListTablesRequest";
  /**
   * The parent namespace.
   *
   * Format: namespaces/{namespace}
   */
  readonly parent: string;
  /**
   * The number of tables to return.
   *
   * Default: 100
   * Maximum: 1000.
   */
  readonly pageSize?: number | undefined;
  /** The continuation token. */
  readonly pageToken?: string | undefined;
}

export interface ListTablesResponse {
  $type: "wings.cluster.ListTablesResponse";
  /** The tables. */
  readonly tables: readonly Table[];
  /** The continuation token. */
  readonly nextPageToken: string;
}

export interface DeleteTableRequest {
  $type: "wings.cluster.DeleteTableRequest";
  /**
   * The table name.
   *
   * Format: namespaces/{namespace}/tables/{table}
   */
  readonly name: string;
}

export interface Table {
  $type: "wings.cluster.Table";
  /**
   * The table name.
   *
   * Format: namespaces/{namespace}/tables/{table}
   */
  readonly name: string;
  /** The table schema. */
  readonly schema: Schema | undefined;
  /** The table description. */
  readonly description?: string | undefined;
  /** The id of the key field. */
  readonly keyFieldId: bigint;
  /** The id of the version field. */
  readonly versionFieldId: bigint;
  /** The id of the field that is used to partition the table. */
  readonly partitionFieldId?: bigint | undefined;
  /** How often to sync data to the target data lake. */
  readonly targetFreshnessSeconds: bigint;
}

export interface AwsConfiguration {
  $type: "wings.cluster.AwsConfiguration";
  /** Bucket name. */
  readonly bucketName: string;
  /** Bucket prefix. */
  readonly prefix?: string | undefined;
  /** / `AWS_ACCESS_KEY_ID` */
  readonly accessKeyId: string;
  /** / `AWS_SECRET_ACCESS_KEY` */
  readonly secretAccessKey: string;
  /** / `AWS_DEFAULT_REGION` */
  readonly region?: string | undefined;
}

export interface AzureConfiguration {
  $type: "wings.cluster.AzureConfiguration";
  /** Azure container name. */
  readonly containerName: string;
  /** Container prefix. */
  readonly prefix?: string | undefined;
  /** `AZURE_STORAGE_ACCOUNT_NAME` */
  readonly storageAccountName: string;
  /** `AZURE_STORAGE_ACCOUNT_KEY` */
  readonly storageAccountKey: string;
}

export interface GoogleConfiguration {
  $type: "wings.cluster.GoogleConfiguration";
  /** / Bucket name. */
  readonly bucketName: string;
  /** / Bucket prefix. */
  readonly prefix?: string | undefined;
  /** / `GOOGLE_SERVICE_ACCOUNT` */
  readonly serviceAccount: string;
  /** / `GOOGLE_SERVICE_ACCOUNT_KEY` */
  readonly serviceAccountKey: string;
}

export interface S3CompatibleConfiguration {
  $type: "wings.cluster.S3CompatibleConfiguration";
  /** Bucket name. */
  readonly bucketName: string;
  /** Bucket prefix. */
  readonly prefix?: string | undefined;
  /** / `AWS_ACCESS_KEY_ID` */
  readonly accessKeyId: string;
  /** / `AWS_SECRET_ACCESS_KEY` */
  readonly secretAccessKey: string;
  /** / `AWS_DEFAULT_REGION` */
  readonly region?: string | undefined;
  /** / `AWS_ENDPOINT` */
  readonly endpoint: string;
  /** / Allow HTTP connections. */
  readonly allowHttp: boolean;
}

export interface Lake {
  $type: "wings.cluster.Lake";
  /** Lake configuration. */
  readonly lakeConfig?:
    | { readonly $case: "parquet"; readonly parquet: ParquetConfiguration }
    | { readonly $case: "iceberg"; readonly iceberg: IcebergConfiguration }
    | { readonly $case: "delta"; readonly delta: DeltaConfiguration }
    | undefined;
}

export interface IcebergConfiguration {
  $type: "wings.cluster.IcebergConfiguration";
}

export interface ParquetConfiguration {
  $type: "wings.cluster.ParquetConfiguration";
}

export interface DeltaConfiguration {
  $type: "wings.cluster.DeltaConfiguration";
}

function createBaseCreateNamespaceRequest(): CreateNamespaceRequest {
  return { $type: "wings.cluster.CreateNamespaceRequest", namespaceId: "", namespace: undefined };
}

export const CreateNamespaceRequest: MessageFns<
  CreateNamespaceRequest,
  "wings.cluster.CreateNamespaceRequest"
> = {
  $type: "wings.cluster.CreateNamespaceRequest" as const,

  encode(message: CreateNamespaceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.namespaceId !== "") {
      writer.uint32(10).string(message.namespaceId);
    }
    if (message.namespace !== undefined) {
      Namespace.encode(message.namespace, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateNamespaceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateNamespaceRequest() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.namespaceId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.namespace = Namespace.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateNamespaceRequest {
    return {
      $type: CreateNamespaceRequest.$type,
      namespaceId: isSet(object.namespaceId) ? globalThis.String(object.namespaceId) : "",
      namespace: isSet(object.namespace) ? Namespace.fromJSON(object.namespace) : undefined,
    };
  },

  toJSON(message: CreateNamespaceRequest): unknown {
    const obj: any = {};
    if (message.namespaceId !== "") {
      obj.namespaceId = message.namespaceId;
    }
    if (message.namespace !== undefined) {
      obj.namespace = Namespace.toJSON(message.namespace);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateNamespaceRequest>, I>>(
    base?: I,
  ): CreateNamespaceRequest {
    return CreateNamespaceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateNamespaceRequest>, I>>(
    object: I,
  ): CreateNamespaceRequest {
    const message = createBaseCreateNamespaceRequest() as any;
    message.namespaceId = object.namespaceId ?? "";
    message.namespace =
      object.namespace !== undefined && object.namespace !== null
        ? Namespace.fromPartial(object.namespace)
        : undefined;
    return message;
  },
};

messageTypeRegistry.set(CreateNamespaceRequest.$type, CreateNamespaceRequest);

function createBaseUpdateNamespaceRequest(): UpdateNamespaceRequest {
  return {
    $type: "wings.cluster.UpdateNamespaceRequest",
    namespace: undefined,
    updateMask: undefined,
  };
}

export const UpdateNamespaceRequest: MessageFns<
  UpdateNamespaceRequest,
  "wings.cluster.UpdateNamespaceRequest"
> = {
  $type: "wings.cluster.UpdateNamespaceRequest" as const,

  encode(message: UpdateNamespaceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.namespace !== undefined) {
      Namespace.encode(message.namespace, writer.uint32(10).fork()).join();
    }
    if (message.updateMask !== undefined) {
      FieldMask.encode(FieldMask.wrap(message.updateMask), writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateNamespaceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateNamespaceRequest() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.namespace = Namespace.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.updateMask = FieldMask.unwrap(FieldMask.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateNamespaceRequest {
    return {
      $type: UpdateNamespaceRequest.$type,
      namespace: isSet(object.namespace) ? Namespace.fromJSON(object.namespace) : undefined,
      updateMask: isSet(object.updateMask)
        ? FieldMask.unwrap(FieldMask.fromJSON(object.updateMask))
        : undefined,
    };
  },

  toJSON(message: UpdateNamespaceRequest): unknown {
    const obj: any = {};
    if (message.namespace !== undefined) {
      obj.namespace = Namespace.toJSON(message.namespace);
    }
    if (message.updateMask !== undefined) {
      obj.updateMask = FieldMask.toJSON(FieldMask.wrap(message.updateMask));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateNamespaceRequest>, I>>(
    base?: I,
  ): UpdateNamespaceRequest {
    return UpdateNamespaceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateNamespaceRequest>, I>>(
    object: I,
  ): UpdateNamespaceRequest {
    const message = createBaseUpdateNamespaceRequest() as any;
    message.namespace =
      object.namespace !== undefined && object.namespace !== null
        ? Namespace.fromPartial(object.namespace)
        : undefined;
    message.updateMask = object.updateMask ?? undefined;
    return message;
  },
};

messageTypeRegistry.set(UpdateNamespaceRequest.$type, UpdateNamespaceRequest);

function createBaseGetNamespaceRequest(): GetNamespaceRequest {
  return { $type: "wings.cluster.GetNamespaceRequest", name: "" };
}

export const GetNamespaceRequest: MessageFns<
  GetNamespaceRequest,
  "wings.cluster.GetNamespaceRequest"
> = {
  $type: "wings.cluster.GetNamespaceRequest" as const,

  encode(message: GetNamespaceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetNamespaceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetNamespaceRequest() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetNamespaceRequest {
    return {
      $type: GetNamespaceRequest.$type,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
    };
  },

  toJSON(message: GetNamespaceRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetNamespaceRequest>, I>>(base?: I): GetNamespaceRequest {
    return GetNamespaceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetNamespaceRequest>, I>>(
    object: I,
  ): GetNamespaceRequest {
    const message = createBaseGetNamespaceRequest() as any;
    message.name = object.name ?? "";
    return message;
  },
};

messageTypeRegistry.set(GetNamespaceRequest.$type, GetNamespaceRequest);

function createBaseListNamespacesRequest(): ListNamespacesRequest {
  return {
    $type: "wings.cluster.ListNamespacesRequest",
    pageSize: undefined,
    pageToken: undefined,
  };
}

export const ListNamespacesRequest: MessageFns<
  ListNamespacesRequest,
  "wings.cluster.ListNamespacesRequest"
> = {
  $type: "wings.cluster.ListNamespacesRequest" as const,

  encode(message: ListNamespacesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pageSize !== undefined) {
      writer.uint32(8).int32(message.pageSize);
    }
    if (message.pageToken !== undefined) {
      writer.uint32(18).string(message.pageToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListNamespacesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListNamespacesRequest() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.pageSize = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pageToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListNamespacesRequest {
    return {
      $type: ListNamespacesRequest.$type,
      pageSize: isSet(object.pageSize) ? globalThis.Number(object.pageSize) : undefined,
      pageToken: isSet(object.pageToken) ? globalThis.String(object.pageToken) : undefined,
    };
  },

  toJSON(message: ListNamespacesRequest): unknown {
    const obj: any = {};
    if (message.pageSize !== undefined) {
      obj.pageSize = Math.round(message.pageSize);
    }
    if (message.pageToken !== undefined) {
      obj.pageToken = message.pageToken;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListNamespacesRequest>, I>>(base?: I): ListNamespacesRequest {
    return ListNamespacesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListNamespacesRequest>, I>>(
    object: I,
  ): ListNamespacesRequest {
    const message = createBaseListNamespacesRequest() as any;
    message.pageSize = object.pageSize ?? undefined;
    message.pageToken = object.pageToken ?? undefined;
    return message;
  },
};

messageTypeRegistry.set(ListNamespacesRequest.$type, ListNamespacesRequest);

function createBaseListNamespacesResponse(): ListNamespacesResponse {
  return {
    $type: "wings.cluster.ListNamespacesResponse",
    namespaces: [],
    nextPageToken: undefined,
  };
}

export const ListNamespacesResponse: MessageFns<
  ListNamespacesResponse,
  "wings.cluster.ListNamespacesResponse"
> = {
  $type: "wings.cluster.ListNamespacesResponse" as const,

  encode(message: ListNamespacesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.namespaces) {
      Namespace.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.nextPageToken !== undefined) {
      writer.uint32(18).string(message.nextPageToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListNamespacesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListNamespacesResponse() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.namespaces.push(Namespace.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nextPageToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListNamespacesResponse {
    return {
      $type: ListNamespacesResponse.$type,
      namespaces: globalThis.Array.isArray(object?.namespaces)
        ? object.namespaces.map((e: any) => Namespace.fromJSON(e))
        : [],
      nextPageToken: isSet(object.nextPageToken)
        ? globalThis.String(object.nextPageToken)
        : undefined,
    };
  },

  toJSON(message: ListNamespacesResponse): unknown {
    const obj: any = {};
    if (message.namespaces?.length) {
      obj.namespaces = message.namespaces.map((e) => Namespace.toJSON(e));
    }
    if (message.nextPageToken !== undefined) {
      obj.nextPageToken = message.nextPageToken;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListNamespacesResponse>, I>>(
    base?: I,
  ): ListNamespacesResponse {
    return ListNamespacesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListNamespacesResponse>, I>>(
    object: I,
  ): ListNamespacesResponse {
    const message = createBaseListNamespacesResponse() as any;
    message.namespaces = object.namespaces?.map((e) => Namespace.fromPartial(e)) || [];
    message.nextPageToken = object.nextPageToken ?? undefined;
    return message;
  },
};

messageTypeRegistry.set(ListNamespacesResponse.$type, ListNamespacesResponse);

function createBaseDeleteNamespaceRequest(): DeleteNamespaceRequest {
  return { $type: "wings.cluster.DeleteNamespaceRequest", name: "" };
}

export const DeleteNamespaceRequest: MessageFns<
  DeleteNamespaceRequest,
  "wings.cluster.DeleteNamespaceRequest"
> = {
  $type: "wings.cluster.DeleteNamespaceRequest" as const,

  encode(message: DeleteNamespaceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteNamespaceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteNamespaceRequest() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteNamespaceRequest {
    return {
      $type: DeleteNamespaceRequest.$type,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
    };
  },

  toJSON(message: DeleteNamespaceRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteNamespaceRequest>, I>>(
    base?: I,
  ): DeleteNamespaceRequest {
    return DeleteNamespaceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteNamespaceRequest>, I>>(
    object: I,
  ): DeleteNamespaceRequest {
    const message = createBaseDeleteNamespaceRequest() as any;
    message.name = object.name ?? "";
    return message;
  },
};

messageTypeRegistry.set(DeleteNamespaceRequest.$type, DeleteNamespaceRequest);

function createBaseNamespace(): Namespace {
  return { $type: "wings.cluster.Namespace", name: "", objectStore: undefined, lake: undefined };
}

export const Namespace: MessageFns<Namespace, "wings.cluster.Namespace"> = {
  $type: "wings.cluster.Namespace" as const,

  encode(message: Namespace, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.objectStore !== undefined) {
      ObjectStore.encode(message.objectStore, writer.uint32(18).fork()).join();
    }
    if (message.lake !== undefined) {
      Lake.encode(message.lake, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Namespace {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNamespace() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.objectStore = ObjectStore.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.lake = Lake.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Namespace {
    return {
      $type: Namespace.$type,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      objectStore: isSet(object.objectStore) ? ObjectStore.fromJSON(object.objectStore) : undefined,
      lake: isSet(object.lake) ? Lake.fromJSON(object.lake) : undefined,
    };
  },

  toJSON(message: Namespace): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.objectStore !== undefined) {
      obj.objectStore = ObjectStore.toJSON(message.objectStore);
    }
    if (message.lake !== undefined) {
      obj.lake = Lake.toJSON(message.lake);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Namespace>, I>>(base?: I): Namespace {
    return Namespace.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Namespace>, I>>(object: I): Namespace {
    const message = createBaseNamespace() as any;
    message.name = object.name ?? "";
    message.objectStore =
      object.objectStore !== undefined && object.objectStore !== null
        ? ObjectStore.fromPartial(object.objectStore)
        : undefined;
    message.lake =
      object.lake !== undefined && object.lake !== null ? Lake.fromPartial(object.lake) : undefined;
    return message;
  },
};

messageTypeRegistry.set(Namespace.$type, Namespace);

function createBaseObjectStore(): ObjectStore {
  return { $type: "wings.cluster.ObjectStore", objectStoreConfig: undefined };
}

export const ObjectStore: MessageFns<ObjectStore, "wings.cluster.ObjectStore"> = {
  $type: "wings.cluster.ObjectStore" as const,

  encode(message: ObjectStore, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    switch (message.objectStoreConfig?.$case) {
      case "aws":
        AwsConfiguration.encode(message.objectStoreConfig.aws, writer.uint32(18).fork()).join();
        break;
      case "azure":
        AzureConfiguration.encode(message.objectStoreConfig.azure, writer.uint32(26).fork()).join();
        break;
      case "google":
        GoogleConfiguration.encode(
          message.objectStoreConfig.google,
          writer.uint32(34).fork(),
        ).join();
        break;
      case "s3Compatible":
        S3CompatibleConfiguration.encode(
          message.objectStoreConfig.s3Compatible,
          writer.uint32(42).fork(),
        ).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ObjectStore {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseObjectStore() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.objectStoreConfig = {
            $case: "aws",
            aws: AwsConfiguration.decode(reader, reader.uint32()),
          };
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.objectStoreConfig = {
            $case: "azure",
            azure: AzureConfiguration.decode(reader, reader.uint32()),
          };
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.objectStoreConfig = {
            $case: "google",
            google: GoogleConfiguration.decode(reader, reader.uint32()),
          };
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.objectStoreConfig = {
            $case: "s3Compatible",
            s3Compatible: S3CompatibleConfiguration.decode(reader, reader.uint32()),
          };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ObjectStore {
    return {
      $type: ObjectStore.$type,
      objectStoreConfig: isSet(object.aws)
        ? { $case: "aws", aws: AwsConfiguration.fromJSON(object.aws) }
        : isSet(object.azure)
          ? { $case: "azure", azure: AzureConfiguration.fromJSON(object.azure) }
          : isSet(object.google)
            ? { $case: "google", google: GoogleConfiguration.fromJSON(object.google) }
            : isSet(object.s3Compatible)
              ? {
                  $case: "s3Compatible",
                  s3Compatible: S3CompatibleConfiguration.fromJSON(object.s3Compatible),
                }
              : undefined,
    };
  },

  toJSON(message: ObjectStore): unknown {
    const obj: any = {};
    if (message.objectStoreConfig?.$case === "aws") {
      obj.aws = AwsConfiguration.toJSON(message.objectStoreConfig.aws);
    } else if (message.objectStoreConfig?.$case === "azure") {
      obj.azure = AzureConfiguration.toJSON(message.objectStoreConfig.azure);
    } else if (message.objectStoreConfig?.$case === "google") {
      obj.google = GoogleConfiguration.toJSON(message.objectStoreConfig.google);
    } else if (message.objectStoreConfig?.$case === "s3Compatible") {
      obj.s3Compatible = S3CompatibleConfiguration.toJSON(message.objectStoreConfig.s3Compatible);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ObjectStore>, I>>(base?: I): ObjectStore {
    return ObjectStore.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ObjectStore>, I>>(object: I): ObjectStore {
    const message = createBaseObjectStore() as any;
    switch (object.objectStoreConfig?.$case) {
      case "aws": {
        if (object.objectStoreConfig?.aws !== undefined && object.objectStoreConfig?.aws !== null) {
          message.objectStoreConfig = {
            $case: "aws",
            aws: AwsConfiguration.fromPartial(object.objectStoreConfig.aws),
          };
        }
        break;
      }
      case "azure": {
        if (
          object.objectStoreConfig?.azure !== undefined &&
          object.objectStoreConfig?.azure !== null
        ) {
          message.objectStoreConfig = {
            $case: "azure",
            azure: AzureConfiguration.fromPartial(object.objectStoreConfig.azure),
          };
        }
        break;
      }
      case "google": {
        if (
          object.objectStoreConfig?.google !== undefined &&
          object.objectStoreConfig?.google !== null
        ) {
          message.objectStoreConfig = {
            $case: "google",
            google: GoogleConfiguration.fromPartial(object.objectStoreConfig.google),
          };
        }
        break;
      }
      case "s3Compatible": {
        if (
          object.objectStoreConfig?.s3Compatible !== undefined &&
          object.objectStoreConfig?.s3Compatible !== null
        ) {
          message.objectStoreConfig = {
            $case: "s3Compatible",
            s3Compatible: S3CompatibleConfiguration.fromPartial(
              object.objectStoreConfig.s3Compatible,
            ),
          };
        }
        break;
      }
    }
    return message;
  },
};

messageTypeRegistry.set(ObjectStore.$type, ObjectStore);

function createBaseCreateTableRequest(): CreateTableRequest {
  return { $type: "wings.cluster.CreateTableRequest", parent: "", tableId: "", table: undefined };
}

export const CreateTableRequest: MessageFns<
  CreateTableRequest,
  "wings.cluster.CreateTableRequest"
> = {
  $type: "wings.cluster.CreateTableRequest" as const,

  encode(message: CreateTableRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.parent !== "") {
      writer.uint32(10).string(message.parent);
    }
    if (message.tableId !== "") {
      writer.uint32(18).string(message.tableId);
    }
    if (message.table !== undefined) {
      Table.encode(message.table, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateTableRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateTableRequest() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.parent = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tableId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.table = Table.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateTableRequest {
    return {
      $type: CreateTableRequest.$type,
      parent: isSet(object.parent) ? globalThis.String(object.parent) : "",
      tableId: isSet(object.tableId) ? globalThis.String(object.tableId) : "",
      table: isSet(object.table) ? Table.fromJSON(object.table) : undefined,
    };
  },

  toJSON(message: CreateTableRequest): unknown {
    const obj: any = {};
    if (message.parent !== "") {
      obj.parent = message.parent;
    }
    if (message.tableId !== "") {
      obj.tableId = message.tableId;
    }
    if (message.table !== undefined) {
      obj.table = Table.toJSON(message.table);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateTableRequest>, I>>(base?: I): CreateTableRequest {
    return CreateTableRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateTableRequest>, I>>(object: I): CreateTableRequest {
    const message = createBaseCreateTableRequest() as any;
    message.parent = object.parent ?? "";
    message.tableId = object.tableId ?? "";
    message.table =
      object.table !== undefined && object.table !== null
        ? Table.fromPartial(object.table)
        : undefined;
    return message;
  },
};

messageTypeRegistry.set(CreateTableRequest.$type, CreateTableRequest);

function createBaseGetTableRequest(): GetTableRequest {
  return { $type: "wings.cluster.GetTableRequest", name: "" };
}

export const GetTableRequest: MessageFns<GetTableRequest, "wings.cluster.GetTableRequest"> = {
  $type: "wings.cluster.GetTableRequest" as const,

  encode(message: GetTableRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTableRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTableRequest() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTableRequest {
    return {
      $type: GetTableRequest.$type,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
    };
  },

  toJSON(message: GetTableRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTableRequest>, I>>(base?: I): GetTableRequest {
    return GetTableRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTableRequest>, I>>(object: I): GetTableRequest {
    const message = createBaseGetTableRequest() as any;
    message.name = object.name ?? "";
    return message;
  },
};

messageTypeRegistry.set(GetTableRequest.$type, GetTableRequest);

function createBaseListTablesRequest(): ListTablesRequest {
  return {
    $type: "wings.cluster.ListTablesRequest",
    parent: "",
    pageSize: undefined,
    pageToken: undefined,
  };
}

export const ListTablesRequest: MessageFns<ListTablesRequest, "wings.cluster.ListTablesRequest"> = {
  $type: "wings.cluster.ListTablesRequest" as const,

  encode(message: ListTablesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.parent !== "") {
      writer.uint32(10).string(message.parent);
    }
    if (message.pageSize !== undefined) {
      writer.uint32(16).int32(message.pageSize);
    }
    if (message.pageToken !== undefined) {
      writer.uint32(26).string(message.pageToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListTablesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListTablesRequest() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.parent = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.pageSize = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pageToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListTablesRequest {
    return {
      $type: ListTablesRequest.$type,
      parent: isSet(object.parent) ? globalThis.String(object.parent) : "",
      pageSize: isSet(object.pageSize) ? globalThis.Number(object.pageSize) : undefined,
      pageToken: isSet(object.pageToken) ? globalThis.String(object.pageToken) : undefined,
    };
  },

  toJSON(message: ListTablesRequest): unknown {
    const obj: any = {};
    if (message.parent !== "") {
      obj.parent = message.parent;
    }
    if (message.pageSize !== undefined) {
      obj.pageSize = Math.round(message.pageSize);
    }
    if (message.pageToken !== undefined) {
      obj.pageToken = message.pageToken;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListTablesRequest>, I>>(base?: I): ListTablesRequest {
    return ListTablesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListTablesRequest>, I>>(object: I): ListTablesRequest {
    const message = createBaseListTablesRequest() as any;
    message.parent = object.parent ?? "";
    message.pageSize = object.pageSize ?? undefined;
    message.pageToken = object.pageToken ?? undefined;
    return message;
  },
};

messageTypeRegistry.set(ListTablesRequest.$type, ListTablesRequest);

function createBaseListTablesResponse(): ListTablesResponse {
  return { $type: "wings.cluster.ListTablesResponse", tables: [], nextPageToken: "" };
}

export const ListTablesResponse: MessageFns<
  ListTablesResponse,
  "wings.cluster.ListTablesResponse"
> = {
  $type: "wings.cluster.ListTablesResponse" as const,

  encode(message: ListTablesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.tables) {
      Table.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.nextPageToken !== "") {
      writer.uint32(18).string(message.nextPageToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListTablesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListTablesResponse() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tables.push(Table.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nextPageToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListTablesResponse {
    return {
      $type: ListTablesResponse.$type,
      tables: globalThis.Array.isArray(object?.tables)
        ? object.tables.map((e: any) => Table.fromJSON(e))
        : [],
      nextPageToken: isSet(object.nextPageToken) ? globalThis.String(object.nextPageToken) : "",
    };
  },

  toJSON(message: ListTablesResponse): unknown {
    const obj: any = {};
    if (message.tables?.length) {
      obj.tables = message.tables.map((e) => Table.toJSON(e));
    }
    if (message.nextPageToken !== "") {
      obj.nextPageToken = message.nextPageToken;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListTablesResponse>, I>>(base?: I): ListTablesResponse {
    return ListTablesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListTablesResponse>, I>>(object: I): ListTablesResponse {
    const message = createBaseListTablesResponse() as any;
    message.tables = object.tables?.map((e) => Table.fromPartial(e)) || [];
    message.nextPageToken = object.nextPageToken ?? "";
    return message;
  },
};

messageTypeRegistry.set(ListTablesResponse.$type, ListTablesResponse);

function createBaseDeleteTableRequest(): DeleteTableRequest {
  return { $type: "wings.cluster.DeleteTableRequest", name: "" };
}

export const DeleteTableRequest: MessageFns<
  DeleteTableRequest,
  "wings.cluster.DeleteTableRequest"
> = {
  $type: "wings.cluster.DeleteTableRequest" as const,

  encode(message: DeleteTableRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteTableRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteTableRequest() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteTableRequest {
    return {
      $type: DeleteTableRequest.$type,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
    };
  },

  toJSON(message: DeleteTableRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteTableRequest>, I>>(base?: I): DeleteTableRequest {
    return DeleteTableRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteTableRequest>, I>>(object: I): DeleteTableRequest {
    const message = createBaseDeleteTableRequest() as any;
    message.name = object.name ?? "";
    return message;
  },
};

messageTypeRegistry.set(DeleteTableRequest.$type, DeleteTableRequest);

function createBaseTable(): Table {
  return {
    $type: "wings.cluster.Table",
    name: "",
    schema: undefined,
    description: undefined,
    keyFieldId: 0n,
    versionFieldId: 0n,
    partitionFieldId: undefined,
    targetFreshnessSeconds: 0n,
  };
}

export const Table: MessageFns<Table, "wings.cluster.Table"> = {
  $type: "wings.cluster.Table" as const,

  encode(message: Table, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.schema !== undefined) {
      Schema.encode(message.schema, writer.uint32(18).fork()).join();
    }
    if (message.description !== undefined) {
      writer.uint32(26).string(message.description);
    }
    if (message.keyFieldId !== 0n) {
      if (BigInt.asUintN(64, message.keyFieldId) !== message.keyFieldId) {
        throw new globalThis.Error(
          "value provided for field message.keyFieldId of type uint64 too large",
        );
      }
      writer.uint32(32).uint64(message.keyFieldId);
    }
    if (message.versionFieldId !== 0n) {
      if (BigInt.asUintN(64, message.versionFieldId) !== message.versionFieldId) {
        throw new globalThis.Error(
          "value provided for field message.versionFieldId of type uint64 too large",
        );
      }
      writer.uint32(40).uint64(message.versionFieldId);
    }
    if (message.partitionFieldId !== undefined) {
      if (BigInt.asUintN(64, message.partitionFieldId) !== message.partitionFieldId) {
        throw new globalThis.Error(
          "value provided for field message.partitionFieldId of type uint64 too large",
        );
      }
      writer.uint32(48).uint64(message.partitionFieldId);
    }
    if (message.targetFreshnessSeconds !== 0n) {
      if (BigInt.asUintN(64, message.targetFreshnessSeconds) !== message.targetFreshnessSeconds) {
        throw new globalThis.Error(
          "value provided for field message.targetFreshnessSeconds of type uint64 too large",
        );
      }
      writer.uint32(56).uint64(message.targetFreshnessSeconds);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Table {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTable() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.schema = Schema.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.keyFieldId = reader.uint64() as bigint;
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.versionFieldId = reader.uint64() as bigint;
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.partitionFieldId = reader.uint64() as bigint;
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.targetFreshnessSeconds = reader.uint64() as bigint;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Table {
    return {
      $type: Table.$type,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      schema: isSet(object.schema) ? Schema.fromJSON(object.schema) : undefined,
      description: isSet(object.description) ? globalThis.String(object.description) : undefined,
      keyFieldId: isSet(object.keyFieldId) ? BigInt(object.keyFieldId) : 0n,
      versionFieldId: isSet(object.versionFieldId) ? BigInt(object.versionFieldId) : 0n,
      partitionFieldId: isSet(object.partitionFieldId)
        ? BigInt(object.partitionFieldId)
        : undefined,
      targetFreshnessSeconds: isSet(object.targetFreshnessSeconds)
        ? BigInt(object.targetFreshnessSeconds)
        : 0n,
    };
  },

  toJSON(message: Table): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.schema !== undefined) {
      obj.schema = Schema.toJSON(message.schema);
    }
    if (message.description !== undefined) {
      obj.description = message.description;
    }
    if (message.keyFieldId !== 0n) {
      obj.keyFieldId = message.keyFieldId.toString();
    }
    if (message.versionFieldId !== 0n) {
      obj.versionFieldId = message.versionFieldId.toString();
    }
    if (message.partitionFieldId !== undefined) {
      obj.partitionFieldId = message.partitionFieldId.toString();
    }
    if (message.targetFreshnessSeconds !== 0n) {
      obj.targetFreshnessSeconds = message.targetFreshnessSeconds.toString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Table>, I>>(base?: I): Table {
    return Table.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Table>, I>>(object: I): Table {
    const message = createBaseTable() as any;
    message.name = object.name ?? "";
    message.schema =
      object.schema !== undefined && object.schema !== null
        ? Schema.fromPartial(object.schema)
        : undefined;
    message.description = object.description ?? undefined;
    message.keyFieldId = object.keyFieldId ?? 0n;
    message.versionFieldId = object.versionFieldId ?? 0n;
    message.partitionFieldId = object.partitionFieldId ?? undefined;
    message.targetFreshnessSeconds = object.targetFreshnessSeconds ?? 0n;
    return message;
  },
};

messageTypeRegistry.set(Table.$type, Table);

function createBaseAwsConfiguration(): AwsConfiguration {
  return {
    $type: "wings.cluster.AwsConfiguration",
    bucketName: "",
    prefix: undefined,
    accessKeyId: "",
    secretAccessKey: "",
    region: undefined,
  };
}

export const AwsConfiguration: MessageFns<AwsConfiguration, "wings.cluster.AwsConfiguration"> = {
  $type: "wings.cluster.AwsConfiguration" as const,

  encode(message: AwsConfiguration, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bucketName !== "") {
      writer.uint32(10).string(message.bucketName);
    }
    if (message.prefix !== undefined) {
      writer.uint32(18).string(message.prefix);
    }
    if (message.accessKeyId !== "") {
      writer.uint32(26).string(message.accessKeyId);
    }
    if (message.secretAccessKey !== "") {
      writer.uint32(34).string(message.secretAccessKey);
    }
    if (message.region !== undefined) {
      writer.uint32(42).string(message.region);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AwsConfiguration {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAwsConfiguration() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.bucketName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.prefix = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.accessKeyId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.secretAccessKey = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.region = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AwsConfiguration {
    return {
      $type: AwsConfiguration.$type,
      bucketName: isSet(object.bucketName) ? globalThis.String(object.bucketName) : "",
      prefix: isSet(object.prefix) ? globalThis.String(object.prefix) : undefined,
      accessKeyId: isSet(object.accessKeyId) ? globalThis.String(object.accessKeyId) : "",
      secretAccessKey: isSet(object.secretAccessKey)
        ? globalThis.String(object.secretAccessKey)
        : "",
      region: isSet(object.region) ? globalThis.String(object.region) : undefined,
    };
  },

  toJSON(message: AwsConfiguration): unknown {
    const obj: any = {};
    if (message.bucketName !== "") {
      obj.bucketName = message.bucketName;
    }
    if (message.prefix !== undefined) {
      obj.prefix = message.prefix;
    }
    if (message.accessKeyId !== "") {
      obj.accessKeyId = message.accessKeyId;
    }
    if (message.secretAccessKey !== "") {
      obj.secretAccessKey = message.secretAccessKey;
    }
    if (message.region !== undefined) {
      obj.region = message.region;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AwsConfiguration>, I>>(base?: I): AwsConfiguration {
    return AwsConfiguration.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AwsConfiguration>, I>>(object: I): AwsConfiguration {
    const message = createBaseAwsConfiguration() as any;
    message.bucketName = object.bucketName ?? "";
    message.prefix = object.prefix ?? undefined;
    message.accessKeyId = object.accessKeyId ?? "";
    message.secretAccessKey = object.secretAccessKey ?? "";
    message.region = object.region ?? undefined;
    return message;
  },
};

messageTypeRegistry.set(AwsConfiguration.$type, AwsConfiguration);

function createBaseAzureConfiguration(): AzureConfiguration {
  return {
    $type: "wings.cluster.AzureConfiguration",
    containerName: "",
    prefix: undefined,
    storageAccountName: "",
    storageAccountKey: "",
  };
}

export const AzureConfiguration: MessageFns<
  AzureConfiguration,
  "wings.cluster.AzureConfiguration"
> = {
  $type: "wings.cluster.AzureConfiguration" as const,

  encode(message: AzureConfiguration, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.containerName !== "") {
      writer.uint32(10).string(message.containerName);
    }
    if (message.prefix !== undefined) {
      writer.uint32(18).string(message.prefix);
    }
    if (message.storageAccountName !== "") {
      writer.uint32(26).string(message.storageAccountName);
    }
    if (message.storageAccountKey !== "") {
      writer.uint32(34).string(message.storageAccountKey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AzureConfiguration {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAzureConfiguration() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.containerName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.prefix = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.storageAccountName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.storageAccountKey = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AzureConfiguration {
    return {
      $type: AzureConfiguration.$type,
      containerName: isSet(object.containerName) ? globalThis.String(object.containerName) : "",
      prefix: isSet(object.prefix) ? globalThis.String(object.prefix) : undefined,
      storageAccountName: isSet(object.storageAccountName)
        ? globalThis.String(object.storageAccountName)
        : "",
      storageAccountKey: isSet(object.storageAccountKey)
        ? globalThis.String(object.storageAccountKey)
        : "",
    };
  },

  toJSON(message: AzureConfiguration): unknown {
    const obj: any = {};
    if (message.containerName !== "") {
      obj.containerName = message.containerName;
    }
    if (message.prefix !== undefined) {
      obj.prefix = message.prefix;
    }
    if (message.storageAccountName !== "") {
      obj.storageAccountName = message.storageAccountName;
    }
    if (message.storageAccountKey !== "") {
      obj.storageAccountKey = message.storageAccountKey;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AzureConfiguration>, I>>(base?: I): AzureConfiguration {
    return AzureConfiguration.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AzureConfiguration>, I>>(object: I): AzureConfiguration {
    const message = createBaseAzureConfiguration() as any;
    message.containerName = object.containerName ?? "";
    message.prefix = object.prefix ?? undefined;
    message.storageAccountName = object.storageAccountName ?? "";
    message.storageAccountKey = object.storageAccountKey ?? "";
    return message;
  },
};

messageTypeRegistry.set(AzureConfiguration.$type, AzureConfiguration);

function createBaseGoogleConfiguration(): GoogleConfiguration {
  return {
    $type: "wings.cluster.GoogleConfiguration",
    bucketName: "",
    prefix: undefined,
    serviceAccount: "",
    serviceAccountKey: "",
  };
}

export const GoogleConfiguration: MessageFns<
  GoogleConfiguration,
  "wings.cluster.GoogleConfiguration"
> = {
  $type: "wings.cluster.GoogleConfiguration" as const,

  encode(message: GoogleConfiguration, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bucketName !== "") {
      writer.uint32(10).string(message.bucketName);
    }
    if (message.prefix !== undefined) {
      writer.uint32(18).string(message.prefix);
    }
    if (message.serviceAccount !== "") {
      writer.uint32(26).string(message.serviceAccount);
    }
    if (message.serviceAccountKey !== "") {
      writer.uint32(34).string(message.serviceAccountKey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GoogleConfiguration {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGoogleConfiguration() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.bucketName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.prefix = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.serviceAccount = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.serviceAccountKey = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GoogleConfiguration {
    return {
      $type: GoogleConfiguration.$type,
      bucketName: isSet(object.bucketName) ? globalThis.String(object.bucketName) : "",
      prefix: isSet(object.prefix) ? globalThis.String(object.prefix) : undefined,
      serviceAccount: isSet(object.serviceAccount) ? globalThis.String(object.serviceAccount) : "",
      serviceAccountKey: isSet(object.serviceAccountKey)
        ? globalThis.String(object.serviceAccountKey)
        : "",
    };
  },

  toJSON(message: GoogleConfiguration): unknown {
    const obj: any = {};
    if (message.bucketName !== "") {
      obj.bucketName = message.bucketName;
    }
    if (message.prefix !== undefined) {
      obj.prefix = message.prefix;
    }
    if (message.serviceAccount !== "") {
      obj.serviceAccount = message.serviceAccount;
    }
    if (message.serviceAccountKey !== "") {
      obj.serviceAccountKey = message.serviceAccountKey;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GoogleConfiguration>, I>>(base?: I): GoogleConfiguration {
    return GoogleConfiguration.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GoogleConfiguration>, I>>(
    object: I,
  ): GoogleConfiguration {
    const message = createBaseGoogleConfiguration() as any;
    message.bucketName = object.bucketName ?? "";
    message.prefix = object.prefix ?? undefined;
    message.serviceAccount = object.serviceAccount ?? "";
    message.serviceAccountKey = object.serviceAccountKey ?? "";
    return message;
  },
};

messageTypeRegistry.set(GoogleConfiguration.$type, GoogleConfiguration);

function createBaseS3CompatibleConfiguration(): S3CompatibleConfiguration {
  return {
    $type: "wings.cluster.S3CompatibleConfiguration",
    bucketName: "",
    prefix: undefined,
    accessKeyId: "",
    secretAccessKey: "",
    region: undefined,
    endpoint: "",
    allowHttp: false,
  };
}

export const S3CompatibleConfiguration: MessageFns<
  S3CompatibleConfiguration,
  "wings.cluster.S3CompatibleConfiguration"
> = {
  $type: "wings.cluster.S3CompatibleConfiguration" as const,

  encode(
    message: S3CompatibleConfiguration,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.bucketName !== "") {
      writer.uint32(10).string(message.bucketName);
    }
    if (message.prefix !== undefined) {
      writer.uint32(18).string(message.prefix);
    }
    if (message.accessKeyId !== "") {
      writer.uint32(26).string(message.accessKeyId);
    }
    if (message.secretAccessKey !== "") {
      writer.uint32(34).string(message.secretAccessKey);
    }
    if (message.region !== undefined) {
      writer.uint32(42).string(message.region);
    }
    if (message.endpoint !== "") {
      writer.uint32(50).string(message.endpoint);
    }
    if (message.allowHttp !== false) {
      writer.uint32(56).bool(message.allowHttp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): S3CompatibleConfiguration {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseS3CompatibleConfiguration() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.bucketName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.prefix = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.accessKeyId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.secretAccessKey = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.region = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.endpoint = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.allowHttp = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): S3CompatibleConfiguration {
    return {
      $type: S3CompatibleConfiguration.$type,
      bucketName: isSet(object.bucketName) ? globalThis.String(object.bucketName) : "",
      prefix: isSet(object.prefix) ? globalThis.String(object.prefix) : undefined,
      accessKeyId: isSet(object.accessKeyId) ? globalThis.String(object.accessKeyId) : "",
      secretAccessKey: isSet(object.secretAccessKey)
        ? globalThis.String(object.secretAccessKey)
        : "",
      region: isSet(object.region) ? globalThis.String(object.region) : undefined,
      endpoint: isSet(object.endpoint) ? globalThis.String(object.endpoint) : "",
      allowHttp: isSet(object.allowHttp) ? globalThis.Boolean(object.allowHttp) : false,
    };
  },

  toJSON(message: S3CompatibleConfiguration): unknown {
    const obj: any = {};
    if (message.bucketName !== "") {
      obj.bucketName = message.bucketName;
    }
    if (message.prefix !== undefined) {
      obj.prefix = message.prefix;
    }
    if (message.accessKeyId !== "") {
      obj.accessKeyId = message.accessKeyId;
    }
    if (message.secretAccessKey !== "") {
      obj.secretAccessKey = message.secretAccessKey;
    }
    if (message.region !== undefined) {
      obj.region = message.region;
    }
    if (message.endpoint !== "") {
      obj.endpoint = message.endpoint;
    }
    if (message.allowHttp !== false) {
      obj.allowHttp = message.allowHttp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<S3CompatibleConfiguration>, I>>(
    base?: I,
  ): S3CompatibleConfiguration {
    return S3CompatibleConfiguration.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<S3CompatibleConfiguration>, I>>(
    object: I,
  ): S3CompatibleConfiguration {
    const message = createBaseS3CompatibleConfiguration() as any;
    message.bucketName = object.bucketName ?? "";
    message.prefix = object.prefix ?? undefined;
    message.accessKeyId = object.accessKeyId ?? "";
    message.secretAccessKey = object.secretAccessKey ?? "";
    message.region = object.region ?? undefined;
    message.endpoint = object.endpoint ?? "";
    message.allowHttp = object.allowHttp ?? false;
    return message;
  },
};

messageTypeRegistry.set(S3CompatibleConfiguration.$type, S3CompatibleConfiguration);

function createBaseLake(): Lake {
  return { $type: "wings.cluster.Lake", lakeConfig: undefined };
}

export const Lake: MessageFns<Lake, "wings.cluster.Lake"> = {
  $type: "wings.cluster.Lake" as const,

  encode(message: Lake, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    switch (message.lakeConfig?.$case) {
      case "parquet":
        ParquetConfiguration.encode(message.lakeConfig.parquet, writer.uint32(18).fork()).join();
        break;
      case "iceberg":
        IcebergConfiguration.encode(message.lakeConfig.iceberg, writer.uint32(26).fork()).join();
        break;
      case "delta":
        DeltaConfiguration.encode(message.lakeConfig.delta, writer.uint32(34).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Lake {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLake() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.lakeConfig = {
            $case: "parquet",
            parquet: ParquetConfiguration.decode(reader, reader.uint32()),
          };
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.lakeConfig = {
            $case: "iceberg",
            iceberg: IcebergConfiguration.decode(reader, reader.uint32()),
          };
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.lakeConfig = {
            $case: "delta",
            delta: DeltaConfiguration.decode(reader, reader.uint32()),
          };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Lake {
    return {
      $type: Lake.$type,
      lakeConfig: isSet(object.parquet)
        ? { $case: "parquet", parquet: ParquetConfiguration.fromJSON(object.parquet) }
        : isSet(object.iceberg)
          ? { $case: "iceberg", iceberg: IcebergConfiguration.fromJSON(object.iceberg) }
          : isSet(object.delta)
            ? { $case: "delta", delta: DeltaConfiguration.fromJSON(object.delta) }
            : undefined,
    };
  },

  toJSON(message: Lake): unknown {
    const obj: any = {};
    if (message.lakeConfig?.$case === "parquet") {
      obj.parquet = ParquetConfiguration.toJSON(message.lakeConfig.parquet);
    } else if (message.lakeConfig?.$case === "iceberg") {
      obj.iceberg = IcebergConfiguration.toJSON(message.lakeConfig.iceberg);
    } else if (message.lakeConfig?.$case === "delta") {
      obj.delta = DeltaConfiguration.toJSON(message.lakeConfig.delta);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Lake>, I>>(base?: I): Lake {
    return Lake.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Lake>, I>>(object: I): Lake {
    const message = createBaseLake() as any;
    switch (object.lakeConfig?.$case) {
      case "parquet": {
        if (object.lakeConfig?.parquet !== undefined && object.lakeConfig?.parquet !== null) {
          message.lakeConfig = {
            $case: "parquet",
            parquet: ParquetConfiguration.fromPartial(object.lakeConfig.parquet),
          };
        }
        break;
      }
      case "iceberg": {
        if (object.lakeConfig?.iceberg !== undefined && object.lakeConfig?.iceberg !== null) {
          message.lakeConfig = {
            $case: "iceberg",
            iceberg: IcebergConfiguration.fromPartial(object.lakeConfig.iceberg),
          };
        }
        break;
      }
      case "delta": {
        if (object.lakeConfig?.delta !== undefined && object.lakeConfig?.delta !== null) {
          message.lakeConfig = {
            $case: "delta",
            delta: DeltaConfiguration.fromPartial(object.lakeConfig.delta),
          };
        }
        break;
      }
    }
    return message;
  },
};

messageTypeRegistry.set(Lake.$type, Lake);

function createBaseIcebergConfiguration(): IcebergConfiguration {
  return { $type: "wings.cluster.IcebergConfiguration" };
}

export const IcebergConfiguration: MessageFns<
  IcebergConfiguration,
  "wings.cluster.IcebergConfiguration"
> = {
  $type: "wings.cluster.IcebergConfiguration" as const,

  encode(_: IcebergConfiguration, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IcebergConfiguration {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIcebergConfiguration() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): IcebergConfiguration {
    return { $type: IcebergConfiguration.$type };
  },

  toJSON(_: IcebergConfiguration): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<IcebergConfiguration>, I>>(base?: I): IcebergConfiguration {
    return IcebergConfiguration.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IcebergConfiguration>, I>>(_: I): IcebergConfiguration {
    const message = createBaseIcebergConfiguration() as any;
    return message;
  },
};

messageTypeRegistry.set(IcebergConfiguration.$type, IcebergConfiguration);

function createBaseParquetConfiguration(): ParquetConfiguration {
  return { $type: "wings.cluster.ParquetConfiguration" };
}

export const ParquetConfiguration: MessageFns<
  ParquetConfiguration,
  "wings.cluster.ParquetConfiguration"
> = {
  $type: "wings.cluster.ParquetConfiguration" as const,

  encode(_: ParquetConfiguration, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ParquetConfiguration {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParquetConfiguration() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ParquetConfiguration {
    return { $type: ParquetConfiguration.$type };
  },

  toJSON(_: ParquetConfiguration): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ParquetConfiguration>, I>>(base?: I): ParquetConfiguration {
    return ParquetConfiguration.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ParquetConfiguration>, I>>(_: I): ParquetConfiguration {
    const message = createBaseParquetConfiguration() as any;
    return message;
  },
};

messageTypeRegistry.set(ParquetConfiguration.$type, ParquetConfiguration);

function createBaseDeltaConfiguration(): DeltaConfiguration {
  return { $type: "wings.cluster.DeltaConfiguration" };
}

export const DeltaConfiguration: MessageFns<
  DeltaConfiguration,
  "wings.cluster.DeltaConfiguration"
> = {
  $type: "wings.cluster.DeltaConfiguration" as const,

  encode(_: DeltaConfiguration, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeltaConfiguration {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeltaConfiguration() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): DeltaConfiguration {
    return { $type: DeltaConfiguration.$type };
  },

  toJSON(_: DeltaConfiguration): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<DeltaConfiguration>, I>>(base?: I): DeltaConfiguration {
    return DeltaConfiguration.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeltaConfiguration>, I>>(_: I): DeltaConfiguration {
    const message = createBaseDeltaConfiguration() as any;
    return message;
  },
};

messageTypeRegistry.set(DeltaConfiguration.$type, DeltaConfiguration);

/** service to manage cluster resources. */
export type ClusterServiceDefinition = typeof ClusterServiceDefinition;
export const ClusterServiceDefinition = {
  name: "ClusterService",
  fullName: "wings.cluster.ClusterService",
  methods: {
    /** Create a new namespace. */
    createNamespace: {
      name: "CreateNamespace",
      requestType: CreateNamespaceRequest,
      requestStream: false,
      responseType: Namespace,
      responseStream: false,
      options: {},
    },
    /** Update the specified namespace. */
    updateNamespace: {
      name: "UpdateNamespace",
      requestType: UpdateNamespaceRequest,
      requestStream: false,
      responseType: Namespace,
      responseStream: false,
      options: {},
    },
    /** Return the specified namespace. */
    getNamespace: {
      name: "GetNamespace",
      requestType: GetNamespaceRequest,
      requestStream: false,
      responseType: Namespace,
      responseStream: false,
      options: {},
    },
    /** List all namespaces. */
    listNamespaces: {
      name: "ListNamespaces",
      requestType: ListNamespacesRequest,
      requestStream: false,
      responseType: ListNamespacesResponse,
      responseStream: false,
      options: {},
    },
    /**
     * Delete a namespace.
     *
     * The request fails if the namespace has any table.
     */
    deleteNamespace: {
      name: "DeleteNamespace",
      requestType: DeleteNamespaceRequest,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    /** Create a new table belonging to a namespace. */
    createTable: {
      name: "CreateTable",
      requestType: CreateTableRequest,
      requestStream: false,
      responseType: Table,
      responseStream: false,
      options: {},
    },
    /** Return the specified table. */
    getTable: {
      name: "GetTable",
      requestType: GetTableRequest,
      requestStream: false,
      responseType: Table,
      responseStream: false,
      options: {},
    },
    /** List all tables belonging to a namespace. */
    listTables: {
      name: "ListTables",
      requestType: ListTablesRequest,
      requestStream: false,
      responseType: ListTablesResponse,
      responseStream: false,
      options: {},
    },
    /** Delete a table. */
    deleteTable: {
      name: "DeleteTable",
      requestType: DeleteTableRequest,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface ClusterServiceImplementation<CallContextExt = {}> {
  /** Create a new namespace. */
  createNamespace(
    request: CreateNamespaceRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<Namespace>>;
  /** Update the specified namespace. */
  updateNamespace(
    request: UpdateNamespaceRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<Namespace>>;
  /** Return the specified namespace. */
  getNamespace(
    request: GetNamespaceRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<Namespace>>;
  /** List all namespaces. */
  listNamespaces(
    request: ListNamespacesRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<ListNamespacesResponse>>;
  /**
   * Delete a namespace.
   *
   * The request fails if the namespace has any table.
   */
  deleteNamespace(
    request: DeleteNamespaceRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<Empty>>;
  /** Create a new table belonging to a namespace. */
  createTable(
    request: CreateTableRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<Table>>;
  /** Return the specified table. */
  getTable(
    request: GetTableRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<Table>>;
  /** List all tables belonging to a namespace. */
  listTables(
    request: ListTablesRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<ListTablesResponse>>;
  /** Delete a table. */
  deleteTable(
    request: DeleteTableRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<Empty>>;
}

export interface ClusterServiceClient<CallOptionsExt = {}> {
  /** Create a new namespace. */
  createNamespace(
    request: DeepPartial<CreateNamespaceRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<Namespace>;
  /** Update the specified namespace. */
  updateNamespace(
    request: DeepPartial<UpdateNamespaceRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<Namespace>;
  /** Return the specified namespace. */
  getNamespace(
    request: DeepPartial<GetNamespaceRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<Namespace>;
  /** List all namespaces. */
  listNamespaces(
    request: DeepPartial<ListNamespacesRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ListNamespacesResponse>;
  /**
   * Delete a namespace.
   *
   * The request fails if the namespace has any table.
   */
  deleteNamespace(
    request: DeepPartial<DeleteNamespaceRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<Empty>;
  /** Create a new table belonging to a namespace. */
  createTable(
    request: DeepPartial<CreateTableRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<Table>;
  /** Return the specified table. */
  getTable(
    request: DeepPartial<GetTableRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<Table>;
  /** List all tables belonging to a namespace. */
  listTables(
    request: DeepPartial<ListTablesRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ListTablesResponse>;
  /** Delete a table. */
  deleteTable(
    request: DeepPartial<DeleteTableRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<Empty>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends { readonly $case: string }
        ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { readonly $case: T["$case"] }
        : T extends {}
          ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
          : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P> | "$type">]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
