// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: wings/resources.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

import { messageTypeRegistry } from "../typeRegistry.js";

export const protobufPackage = "wings.resources";

/** this proto file is local to the wings package */

export interface Empty {
  $type: "wings.resources.Empty";
}

export interface PartitionValue {
  $type: "wings.resources.PartitionValue";
  readonly value?:
    | { readonly $case: "null"; readonly null: Empty }
    | { readonly $case: "int8"; readonly int8: number }
    | { readonly $case: "int16"; readonly int16: number }
    | { readonly $case: "int32"; readonly int32: number }
    | { readonly $case: "int64"; readonly int64: bigint }
    | { readonly $case: "uint8"; readonly uint8: number }
    | { readonly $case: "uint16"; readonly uint16: number }
    | { readonly $case: "uint32"; readonly uint32: number }
    | { readonly $case: "uint64"; readonly uint64: bigint }
    | { readonly $case: "string"; readonly string: string }
    | { readonly $case: "bytes"; readonly bytes: Uint8Array }
    | { readonly $case: "boolean"; readonly boolean: boolean }
    | undefined;
}

function createBaseEmpty(): Empty {
  return { $type: "wings.resources.Empty" };
}

export const Empty: MessageFns<Empty, "wings.resources.Empty"> = {
  $type: "wings.resources.Empty" as const,

  encode(_: Empty, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Empty {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmpty() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Empty {
    return { $type: Empty.$type };
  },

  toJSON(_: Empty): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<Empty>, I>>(base?: I): Empty {
    return Empty.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Empty>, I>>(_: I): Empty {
    const message = createBaseEmpty() as any;
    return message;
  },
};

messageTypeRegistry.set(Empty.$type, Empty);

function createBasePartitionValue(): PartitionValue {
  return { $type: "wings.resources.PartitionValue", value: undefined };
}

export const PartitionValue: MessageFns<PartitionValue, "wings.resources.PartitionValue"> = {
  $type: "wings.resources.PartitionValue" as const,

  encode(message: PartitionValue, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    switch (message.value?.$case) {
      case "null":
        Empty.encode(message.value.null, writer.uint32(10).fork()).join();
        break;
      case "int8":
        writer.uint32(16).int32(message.value.int8);
        break;
      case "int16":
        writer.uint32(24).int32(message.value.int16);
        break;
      case "int32":
        writer.uint32(32).int32(message.value.int32);
        break;
      case "int64":
        if (BigInt.asIntN(64, message.value.int64) !== message.value.int64) {
          throw new globalThis.Error(
            "value provided for field message.value.int64 of type int64 too large",
          );
        }
        writer.uint32(40).int64(message.value.int64);
        break;
      case "uint8":
        writer.uint32(48).uint32(message.value.uint8);
        break;
      case "uint16":
        writer.uint32(56).uint32(message.value.uint16);
        break;
      case "uint32":
        writer.uint32(64).uint32(message.value.uint32);
        break;
      case "uint64":
        if (BigInt.asUintN(64, message.value.uint64) !== message.value.uint64) {
          throw new globalThis.Error(
            "value provided for field message.value.uint64 of type uint64 too large",
          );
        }
        writer.uint32(72).uint64(message.value.uint64);
        break;
      case "string":
        writer.uint32(82).string(message.value.string);
        break;
      case "bytes":
        writer.uint32(90).bytes(message.value.bytes);
        break;
      case "boolean":
        writer.uint32(96).bool(message.value.boolean);
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PartitionValue {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePartitionValue() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.value = { $case: "null", null: Empty.decode(reader, reader.uint32()) };
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = { $case: "int8", int8: reader.int32() };
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.value = { $case: "int16", int16: reader.int32() };
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.value = { $case: "int32", int32: reader.int32() };
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.value = { $case: "int64", int64: reader.int64() as bigint };
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.value = { $case: "uint8", uint8: reader.uint32() };
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.value = { $case: "uint16", uint16: reader.uint32() };
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.value = { $case: "uint32", uint32: reader.uint32() };
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.value = { $case: "uint64", uint64: reader.uint64() as bigint };
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.value = { $case: "string", string: reader.string() };
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.value = { $case: "bytes", bytes: reader.bytes() };
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.value = { $case: "boolean", boolean: reader.bool() };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PartitionValue {
    return {
      $type: PartitionValue.$type,
      value: isSet(object.null)
        ? { $case: "null", null: Empty.fromJSON(object.null) }
        : isSet(object.int8)
          ? { $case: "int8", int8: globalThis.Number(object.int8) }
          : isSet(object.int16)
            ? { $case: "int16", int16: globalThis.Number(object.int16) }
            : isSet(object.int32)
              ? { $case: "int32", int32: globalThis.Number(object.int32) }
              : isSet(object.int64)
                ? { $case: "int64", int64: BigInt(object.int64) }
                : isSet(object.uint8)
                  ? { $case: "uint8", uint8: globalThis.Number(object.uint8) }
                  : isSet(object.uint16)
                    ? { $case: "uint16", uint16: globalThis.Number(object.uint16) }
                    : isSet(object.uint32)
                      ? { $case: "uint32", uint32: globalThis.Number(object.uint32) }
                      : isSet(object.uint64)
                        ? { $case: "uint64", uint64: BigInt(object.uint64) }
                        : isSet(object.string)
                          ? { $case: "string", string: globalThis.String(object.string) }
                          : isSet(object.bytes)
                            ? { $case: "bytes", bytes: bytesFromBase64(object.bytes) }
                            : isSet(object.boolean)
                              ? { $case: "boolean", boolean: globalThis.Boolean(object.boolean) }
                              : undefined,
    };
  },

  toJSON(message: PartitionValue): unknown {
    const obj: any = {};
    if (message.value?.$case === "null") {
      obj.null = Empty.toJSON(message.value.null);
    } else if (message.value?.$case === "int8") {
      obj.int8 = Math.round(message.value.int8);
    } else if (message.value?.$case === "int16") {
      obj.int16 = Math.round(message.value.int16);
    } else if (message.value?.$case === "int32") {
      obj.int32 = Math.round(message.value.int32);
    } else if (message.value?.$case === "int64") {
      obj.int64 = message.value.int64.toString();
    } else if (message.value?.$case === "uint8") {
      obj.uint8 = Math.round(message.value.uint8);
    } else if (message.value?.$case === "uint16") {
      obj.uint16 = Math.round(message.value.uint16);
    } else if (message.value?.$case === "uint32") {
      obj.uint32 = Math.round(message.value.uint32);
    } else if (message.value?.$case === "uint64") {
      obj.uint64 = message.value.uint64.toString();
    } else if (message.value?.$case === "string") {
      obj.string = message.value.string;
    } else if (message.value?.$case === "bytes") {
      obj.bytes = base64FromBytes(message.value.bytes);
    } else if (message.value?.$case === "boolean") {
      obj.boolean = message.value.boolean;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PartitionValue>, I>>(base?: I): PartitionValue {
    return PartitionValue.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PartitionValue>, I>>(object: I): PartitionValue {
    const message = createBasePartitionValue() as any;
    switch (object.value?.$case) {
      case "null": {
        if (object.value?.null !== undefined && object.value?.null !== null) {
          message.value = { $case: "null", null: Empty.fromPartial(object.value.null) };
        }
        break;
      }
      case "int8": {
        if (object.value?.int8 !== undefined && object.value?.int8 !== null) {
          message.value = { $case: "int8", int8: object.value.int8 };
        }
        break;
      }
      case "int16": {
        if (object.value?.int16 !== undefined && object.value?.int16 !== null) {
          message.value = { $case: "int16", int16: object.value.int16 };
        }
        break;
      }
      case "int32": {
        if (object.value?.int32 !== undefined && object.value?.int32 !== null) {
          message.value = { $case: "int32", int32: object.value.int32 };
        }
        break;
      }
      case "int64": {
        if (object.value?.int64 !== undefined && object.value?.int64 !== null) {
          message.value = { $case: "int64", int64: object.value.int64 };
        }
        break;
      }
      case "uint8": {
        if (object.value?.uint8 !== undefined && object.value?.uint8 !== null) {
          message.value = { $case: "uint8", uint8: object.value.uint8 };
        }
        break;
      }
      case "uint16": {
        if (object.value?.uint16 !== undefined && object.value?.uint16 !== null) {
          message.value = { $case: "uint16", uint16: object.value.uint16 };
        }
        break;
      }
      case "uint32": {
        if (object.value?.uint32 !== undefined && object.value?.uint32 !== null) {
          message.value = { $case: "uint32", uint32: object.value.uint32 };
        }
        break;
      }
      case "uint64": {
        if (object.value?.uint64 !== undefined && object.value?.uint64 !== null) {
          message.value = { $case: "uint64", uint64: object.value.uint64 };
        }
        break;
      }
      case "string": {
        if (object.value?.string !== undefined && object.value?.string !== null) {
          message.value = { $case: "string", string: object.value.string };
        }
        break;
      }
      case "bytes": {
        if (object.value?.bytes !== undefined && object.value?.bytes !== null) {
          message.value = { $case: "bytes", bytes: object.value.bytes };
        }
        break;
      }
      case "boolean": {
        if (object.value?.boolean !== undefined && object.value?.boolean !== null) {
          message.value = { $case: "boolean", boolean: object.value.boolean };
        }
        break;
      }
    }
    return message;
  },
};

messageTypeRegistry.set(PartitionValue.$type, PartitionValue);

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends { readonly $case: string }
        ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { readonly $case: T["$case"] }
        : T extends {}
          ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
          : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P> | "$type">]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
