/**
 * Adapted from the Operator SDK Memcached tutorial:
 * https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/
 */
import { NodeRuntime, NodeServices } from "@effect/platform-node";
import * as k8s from "@kubernetes/client-node";
import { Cause, Console, Effect, FileSystem, Layer, Option } from "effect";
import { Argument, Command } from "effect/unstable/cli";

import packageJson from "../package.json";
import { Kubernetes, KubernetesConfig } from "../src";
import { Controller, Operator, Reconcile, Resource } from "../src/operator";
import { Memcached, MemcachedCrd, type Memcached as MemcachedObject } from "./memcached";

const FIELD_MANAGER = "memcached-operator";

const reconcile = (key: Resource.ResourceKey) =>
  Effect.gen(function* () {
    const memcached = yield* Resource.get(Memcached, key);
    if (Option.isNone(memcached)) return Reconcile.complete;

    if (key.namespace === undefined) {
      return yield* new Cause.IllegalArgumentError("namespace is required");
    }
    const namespace = key.namespace;
    const desired = deploymentFor(memcached.value);

    yield* Operator.applyDeployment(namespace, key.name, desired, FIELD_MANAGER);

    const deployment = yield* Kubernetes.readNamespacedDeployment({ namespace, name: key.name });
    const readyReplicas = Option.match(deployment, {
      onNone: () => 0,
      onSome: (current) => current.status?.readyReplicas ?? 0,
    });
    const wantedReplicas = memcached.value.spec.size;

    yield* Operator.applyStatus(
      Memcached,
      key,
      {
        readyReplicas,
        phase: readyReplicas >= wantedReplicas ? "Ready" : "Progressing",
      },
      `${FIELD_MANAGER}/status`,
    );

    return readyReplicas >= wantedReplicas
      ? Reconcile.complete
      : Reconcile.requeueAfter("5 seconds");
  });

const deploymentFor = (memcached: MemcachedObject): k8s.V1Deployment => {
  const name = memcached.metadata?.name ?? "memcached";
  const namespace = memcached.metadata?.namespace ?? "default";
  const labels = { app: "memcached", "cache.example.com/name": name };
  const ownerReferences =
    memcached.metadata?.uid === undefined
      ? []
      : [
          {
            apiVersion: "cache.example.com/v1alpha1",
            kind: "Memcached",
            name,
            uid: memcached.metadata.uid,
            controller: true,
            blockOwnerDeletion: true,
          },
        ];

  return {
    apiVersion: "apps/v1",
    kind: "Deployment",
    metadata: {
      name,
      namespace,
      labels,
      ownerReferences,
    },
    spec: {
      replicas: memcached.spec.size,
      selector: { matchLabels: labels },
      template: {
        metadata: { labels },
        spec: {
          containers: [
            {
              name: "memcached",
              image: "memcached:1.6",
              ports: [{ containerPort: 11211, name: "memcached" }],
            },
          ],
        },
      },
    },
  };
};

const MainLive = Controller.layer({
  name: "memcached-operator",
  resource: Memcached,
  resyncInterval: "30 seconds",
  reconcile,
  onGiveUp: (key, cause) =>
    Operator.applyStatus(
      Memcached,
      key,
      { phase: "Failed", message: Cause.pretty(cause) },
      `${FIELD_MANAGER}/status`,
    ).pipe(Effect.ignore({ log: true })),
}).pipe(Layer.provide(KubernetesConfig.layerDefault));

const startCommand = Command.make("start", {}, () => Layer.launch(MainLive)).pipe(
  Command.withDescription("Start the Memcached operator"),
);

const outputArgument = Argument.string("output").pipe(
  Argument.withDescription("Write the generated YAML to this file"),
  Argument.optional,
);

const generateCrdCommand = Command.make("generate-crd", { output: outputArgument }, ({ output }) =>
  Effect.gen(function* () {
    const crd = yield* MemcachedCrd;
    const yaml =
      "# Generated by the Memcached example. Do not edit manually.\n" + k8s.dumpYaml(crd).trimEnd();

    yield* Option.match(output, {
      onNone: () => Console.log(yaml),
      onSome: (path) =>
        Effect.gen(function* () {
          const fs = yield* FileSystem.FileSystem;
          yield* fs.writeFileString(path, `${yaml}\n`);
          yield* Console.log(`Generated ${path}`);
        }),
    });
  }),
).pipe(Command.withDescription("Generate the Memcached CustomResourceDefinition YAML"));

const program = Command.make("memcached").pipe(
  Command.withDescription("Run the Effect Kubernetes Memcached example"),
  Command.withSubcommands([startCommand, generateCrdCommand]),
);

Command.run(program, { version: packageJson.version }).pipe(
  Effect.provide(NodeServices.layer),
  Effect.scoped,
  NodeRuntime.runMain,
);
