// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: schema/arrow_type.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { messageTypeRegistry } from "../typeRegistry.js";

export const protobufPackage = "wings.schema";

export enum TimeUnit {
  UNSPECIFIED = 0,
  SECOND = 1,
  MILLISECOND = 2,
  MICROSECOND = 3,
  NANOSECOND = 4,
  UNRECOGNIZED = -1,
}

export function timeUnitFromJSON(object: any): TimeUnit {
  switch (object) {
    case 0:
    case "TIME_UNIT_UNSPECIFIED":
      return TimeUnit.UNSPECIFIED;
    case 1:
    case "TIME_UNIT_SECOND":
      return TimeUnit.SECOND;
    case 2:
    case "TIME_UNIT_MILLISECOND":
      return TimeUnit.MILLISECOND;
    case 3:
    case "TIME_UNIT_MICROSECOND":
      return TimeUnit.MICROSECOND;
    case 4:
    case "TIME_UNIT_NANOSECOND":
      return TimeUnit.NANOSECOND;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TimeUnit.UNRECOGNIZED;
  }
}

export function timeUnitToJSON(object: TimeUnit): string {
  switch (object) {
    case TimeUnit.UNSPECIFIED:
      return "TIME_UNIT_UNSPECIFIED";
    case TimeUnit.SECOND:
      return "TIME_UNIT_SECOND";
    case TimeUnit.MILLISECOND:
      return "TIME_UNIT_MILLISECOND";
    case TimeUnit.MICROSECOND:
      return "TIME_UNIT_MICROSECOND";
    case TimeUnit.NANOSECOND:
      return "TIME_UNIT_NANOSECOND";
    case TimeUnit.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Schema {
  $type: "wings.schema.Schema";
  readonly fields: readonly Field[];
  readonly metadata: Map<string, string>;
}

export interface Schema_MetadataEntry {
  $type: "wings.schema.Schema.MetadataEntry";
  readonly key: string;
  readonly value: string;
}

export interface Field {
  $type: "wings.schema.Field";
  readonly name: string;
  readonly id: bigint;
  readonly arrowType: ArrowType | undefined;
  readonly nullable: boolean;
  readonly metadata: Map<string, string>;
}

export interface Field_MetadataEntry {
  $type: "wings.schema.Field.MetadataEntry";
  readonly key: string;
  readonly value: string;
}

export interface EmptyMessage {
  $type: "wings.schema.EmptyMessage";
}

export interface Timestamp {
  $type: "wings.schema.Timestamp";
  readonly timeUnit: TimeUnit;
  readonly timezone: string;
}

export interface List {
  $type: "wings.schema.List";
  readonly fieldType: Field | undefined;
}

export interface Struct {
  $type: "wings.schema.Struct";
  readonly subFieldTypes: readonly Field[];
}

export interface ArrowType {
  $type: "wings.schema.ArrowType";
  readonly arrowTypeEnum?:
    | { readonly $case: "none"; readonly none: EmptyMessage }
    | { readonly $case: "bool"; readonly bool: EmptyMessage }
    | { readonly $case: "uint8"; readonly uint8: EmptyMessage }
    | { readonly $case: "int8"; readonly int8: EmptyMessage }
    | { readonly $case: "uint16"; readonly uint16: EmptyMessage }
    | { readonly $case: "int16"; readonly int16: EmptyMessage }
    | { readonly $case: "uint32"; readonly uint32: EmptyMessage }
    | { readonly $case: "int32"; readonly int32: EmptyMessage }
    | { readonly $case: "uint64"; readonly uint64: EmptyMessage }
    | { readonly $case: "int64"; readonly int64: EmptyMessage }
    | { readonly $case: "float16"; readonly float16: EmptyMessage }
    | { readonly $case: "float32"; readonly float32: EmptyMessage }
    | { readonly $case: "float64"; readonly float64: EmptyMessage }
    | { readonly $case: "utf8"; readonly utf8: EmptyMessage }
    | { readonly $case: "binary"; readonly binary: EmptyMessage }
    | { readonly $case: "date32"; readonly date32: EmptyMessage }
    | { readonly $case: "date64"; readonly date64: EmptyMessage }
    | { readonly $case: "duration"; readonly duration: TimeUnit }
    | { readonly $case: "timestamp"; readonly timestamp: Timestamp }
    | { readonly $case: "list"; readonly list: List }
    | { readonly $case: "struct"; readonly struct: Struct }
    | undefined;
}

/** A value serialized to bytes */
export interface Datum {
  $type: "wings.schema.Datum";
  readonly type: ArrowType | undefined;
  readonly content: Uint8Array;
}

function createBaseSchema(): Schema {
  return { $type: "wings.schema.Schema", fields: [], metadata: new Map() };
}

export const Schema: MessageFns<Schema, "wings.schema.Schema"> = {
  $type: "wings.schema.Schema" as const,

  encode(message: Schema, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.fields) {
      Field.encode(v!, writer.uint32(10).fork()).join();
    }
    message.metadata.forEach((value, key) => {
      Schema_MetadataEntry.encode(
        { $type: "wings.schema.Schema.MetadataEntry", key: key as any, value },
        writer.uint32(18).fork(),
      ).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Schema {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSchema() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.fields.push(Field.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          const entry2 = Schema_MetadataEntry.decode(reader, reader.uint32());
          if (entry2.value !== undefined) {
            message.metadata.set(entry2.key, entry2.value);
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Schema {
    return {
      $type: Schema.$type,
      fields: globalThis.Array.isArray(object?.fields) ? object.fields.map((e: any) => Field.fromJSON(e)) : [],
      metadata: isObject(object.metadata)
        ? Object.entries(object.metadata).reduce<Map<string, string>>((acc, [key, value]) => {
          acc.set(key, String(value));
          return acc;
        }, new Map())
        : new Map(),
    };
  },

  toJSON(message: Schema): unknown {
    const obj: any = {};
    if (message.fields?.length) {
      obj.fields = message.fields.map((e) => Field.toJSON(e));
    }
    if (message.metadata?.size) {
      obj.metadata = {};
      message.metadata.forEach((v, k) => {
        obj.metadata[k] = v;
      });
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Schema>, I>>(base?: I): Schema {
    return Schema.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Schema>, I>>(object: I): Schema {
    const message = createBaseSchema() as any;
    message.fields = object.fields?.map((e) => Field.fromPartial(e)) || [];
    message.metadata = (() => {
      const m = new Map();
      (object.metadata as Map<string, string> ?? new Map()).forEach((value, key) => {
        if (value !== undefined) {
          m.set(key, globalThis.String(value));
        }
      });
      return m;
    })();
    return message;
  },
};

messageTypeRegistry.set(Schema.$type, Schema);

function createBaseSchema_MetadataEntry(): Schema_MetadataEntry {
  return { $type: "wings.schema.Schema.MetadataEntry", key: "", value: "" };
}

export const Schema_MetadataEntry: MessageFns<Schema_MetadataEntry, "wings.schema.Schema.MetadataEntry"> = {
  $type: "wings.schema.Schema.MetadataEntry" as const,

  encode(message: Schema_MetadataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Schema_MetadataEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSchema_MetadataEntry() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Schema_MetadataEntry {
    return {
      $type: Schema_MetadataEntry.$type,
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: Schema_MetadataEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Schema_MetadataEntry>, I>>(base?: I): Schema_MetadataEntry {
    return Schema_MetadataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Schema_MetadataEntry>, I>>(object: I): Schema_MetadataEntry {
    const message = createBaseSchema_MetadataEntry() as any;
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

messageTypeRegistry.set(Schema_MetadataEntry.$type, Schema_MetadataEntry);

function createBaseField(): Field {
  return { $type: "wings.schema.Field", name: "", id: 0n, arrowType: undefined, nullable: false, metadata: new Map() };
}

export const Field: MessageFns<Field, "wings.schema.Field"> = {
  $type: "wings.schema.Field" as const,

  encode(message: Field, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.id !== 0n) {
      if (BigInt.asUintN(64, message.id) !== message.id) {
        throw new globalThis.Error("value provided for field message.id of type uint64 too large");
      }
      writer.uint32(16).uint64(message.id);
    }
    if (message.arrowType !== undefined) {
      ArrowType.encode(message.arrowType, writer.uint32(26).fork()).join();
    }
    if (message.nullable !== false) {
      writer.uint32(32).bool(message.nullable);
    }
    message.metadata.forEach((value, key) => {
      Field_MetadataEntry.encode(
        { $type: "wings.schema.Field.MetadataEntry", key: key as any, value },
        writer.uint32(42).fork(),
      ).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Field {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseField() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.id = reader.uint64() as bigint;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.arrowType = ArrowType.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.nullable = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          const entry5 = Field_MetadataEntry.decode(reader, reader.uint32());
          if (entry5.value !== undefined) {
            message.metadata.set(entry5.key, entry5.value);
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Field {
    return {
      $type: Field.$type,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      id: isSet(object.id) ? BigInt(object.id) : 0n,
      arrowType: isSet(object.arrowType) ? ArrowType.fromJSON(object.arrowType) : undefined,
      nullable: isSet(object.nullable) ? globalThis.Boolean(object.nullable) : false,
      metadata: isObject(object.metadata)
        ? Object.entries(object.metadata).reduce<Map<string, string>>((acc, [key, value]) => {
          acc.set(key, String(value));
          return acc;
        }, new Map())
        : new Map(),
    };
  },

  toJSON(message: Field): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.id !== 0n) {
      obj.id = message.id.toString();
    }
    if (message.arrowType !== undefined) {
      obj.arrowType = ArrowType.toJSON(message.arrowType);
    }
    if (message.nullable !== false) {
      obj.nullable = message.nullable;
    }
    if (message.metadata?.size) {
      obj.metadata = {};
      message.metadata.forEach((v, k) => {
        obj.metadata[k] = v;
      });
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Field>, I>>(base?: I): Field {
    return Field.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Field>, I>>(object: I): Field {
    const message = createBaseField() as any;
    message.name = object.name ?? "";
    message.id = object.id ?? 0n;
    message.arrowType = (object.arrowType !== undefined && object.arrowType !== null)
      ? ArrowType.fromPartial(object.arrowType)
      : undefined;
    message.nullable = object.nullable ?? false;
    message.metadata = (() => {
      const m = new Map();
      (object.metadata as Map<string, string> ?? new Map()).forEach((value, key) => {
        if (value !== undefined) {
          m.set(key, globalThis.String(value));
        }
      });
      return m;
    })();
    return message;
  },
};

messageTypeRegistry.set(Field.$type, Field);

function createBaseField_MetadataEntry(): Field_MetadataEntry {
  return { $type: "wings.schema.Field.MetadataEntry", key: "", value: "" };
}

export const Field_MetadataEntry: MessageFns<Field_MetadataEntry, "wings.schema.Field.MetadataEntry"> = {
  $type: "wings.schema.Field.MetadataEntry" as const,

  encode(message: Field_MetadataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Field_MetadataEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseField_MetadataEntry() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Field_MetadataEntry {
    return {
      $type: Field_MetadataEntry.$type,
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: Field_MetadataEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Field_MetadataEntry>, I>>(base?: I): Field_MetadataEntry {
    return Field_MetadataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Field_MetadataEntry>, I>>(object: I): Field_MetadataEntry {
    const message = createBaseField_MetadataEntry() as any;
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

messageTypeRegistry.set(Field_MetadataEntry.$type, Field_MetadataEntry);

function createBaseEmptyMessage(): EmptyMessage {
  return { $type: "wings.schema.EmptyMessage" };
}

export const EmptyMessage: MessageFns<EmptyMessage, "wings.schema.EmptyMessage"> = {
  $type: "wings.schema.EmptyMessage" as const,

  encode(_: EmptyMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmptyMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmptyMessage() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): EmptyMessage {
    return { $type: EmptyMessage.$type };
  },

  toJSON(_: EmptyMessage): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<EmptyMessage>, I>>(base?: I): EmptyMessage {
    return EmptyMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmptyMessage>, I>>(_: I): EmptyMessage {
    const message = createBaseEmptyMessage() as any;
    return message;
  },
};

messageTypeRegistry.set(EmptyMessage.$type, EmptyMessage);

function createBaseTimestamp(): Timestamp {
  return { $type: "wings.schema.Timestamp", timeUnit: 0, timezone: "" };
}

export const Timestamp: MessageFns<Timestamp, "wings.schema.Timestamp"> = {
  $type: "wings.schema.Timestamp" as const,

  encode(message: Timestamp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.timeUnit !== 0) {
      writer.uint32(8).int32(message.timeUnit);
    }
    if (message.timezone !== "") {
      writer.uint32(18).string(message.timezone);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Timestamp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTimestamp() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.timeUnit = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.timezone = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Timestamp {
    return {
      $type: Timestamp.$type,
      timeUnit: isSet(object.timeUnit) ? timeUnitFromJSON(object.timeUnit) : 0,
      timezone: isSet(object.timezone) ? globalThis.String(object.timezone) : "",
    };
  },

  toJSON(message: Timestamp): unknown {
    const obj: any = {};
    if (message.timeUnit !== 0) {
      obj.timeUnit = timeUnitToJSON(message.timeUnit);
    }
    if (message.timezone !== "") {
      obj.timezone = message.timezone;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Timestamp>, I>>(base?: I): Timestamp {
    return Timestamp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Timestamp>, I>>(object: I): Timestamp {
    const message = createBaseTimestamp() as any;
    message.timeUnit = object.timeUnit ?? 0;
    message.timezone = object.timezone ?? "";
    return message;
  },
};

messageTypeRegistry.set(Timestamp.$type, Timestamp);

function createBaseList(): List {
  return { $type: "wings.schema.List", fieldType: undefined };
}

export const List: MessageFns<List, "wings.schema.List"> = {
  $type: "wings.schema.List" as const,

  encode(message: List, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fieldType !== undefined) {
      Field.encode(message.fieldType, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): List {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseList() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.fieldType = Field.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): List {
    return { $type: List.$type, fieldType: isSet(object.fieldType) ? Field.fromJSON(object.fieldType) : undefined };
  },

  toJSON(message: List): unknown {
    const obj: any = {};
    if (message.fieldType !== undefined) {
      obj.fieldType = Field.toJSON(message.fieldType);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<List>, I>>(base?: I): List {
    return List.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<List>, I>>(object: I): List {
    const message = createBaseList() as any;
    message.fieldType = (object.fieldType !== undefined && object.fieldType !== null)
      ? Field.fromPartial(object.fieldType)
      : undefined;
    return message;
  },
};

messageTypeRegistry.set(List.$type, List);

function createBaseStruct(): Struct {
  return { $type: "wings.schema.Struct", subFieldTypes: [] };
}

export const Struct: MessageFns<Struct, "wings.schema.Struct"> = {
  $type: "wings.schema.Struct" as const,

  encode(message: Struct, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.subFieldTypes) {
      Field.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Struct {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStruct() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.subFieldTypes.push(Field.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Struct {
    return {
      $type: Struct.$type,
      subFieldTypes: globalThis.Array.isArray(object?.subFieldTypes)
        ? object.subFieldTypes.map((e: any) => Field.fromJSON(e))
        : [],
    };
  },

  toJSON(message: Struct): unknown {
    const obj: any = {};
    if (message.subFieldTypes?.length) {
      obj.subFieldTypes = message.subFieldTypes.map((e) => Field.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Struct>, I>>(base?: I): Struct {
    return Struct.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Struct>, I>>(object: I): Struct {
    const message = createBaseStruct() as any;
    message.subFieldTypes = object.subFieldTypes?.map((e) => Field.fromPartial(e)) || [];
    return message;
  },
};

messageTypeRegistry.set(Struct.$type, Struct);

function createBaseArrowType(): ArrowType {
  return { $type: "wings.schema.ArrowType", arrowTypeEnum: undefined };
}

export const ArrowType: MessageFns<ArrowType, "wings.schema.ArrowType"> = {
  $type: "wings.schema.ArrowType" as const,

  encode(message: ArrowType, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    switch (message.arrowTypeEnum?.$case) {
      case "none":
        EmptyMessage.encode(message.arrowTypeEnum.none, writer.uint32(10).fork()).join();
        break;
      case "bool":
        EmptyMessage.encode(message.arrowTypeEnum.bool, writer.uint32(18).fork()).join();
        break;
      case "uint8":
        EmptyMessage.encode(message.arrowTypeEnum.uint8, writer.uint32(26).fork()).join();
        break;
      case "int8":
        EmptyMessage.encode(message.arrowTypeEnum.int8, writer.uint32(34).fork()).join();
        break;
      case "uint16":
        EmptyMessage.encode(message.arrowTypeEnum.uint16, writer.uint32(42).fork()).join();
        break;
      case "int16":
        EmptyMessage.encode(message.arrowTypeEnum.int16, writer.uint32(50).fork()).join();
        break;
      case "uint32":
        EmptyMessage.encode(message.arrowTypeEnum.uint32, writer.uint32(58).fork()).join();
        break;
      case "int32":
        EmptyMessage.encode(message.arrowTypeEnum.int32, writer.uint32(66).fork()).join();
        break;
      case "uint64":
        EmptyMessage.encode(message.arrowTypeEnum.uint64, writer.uint32(74).fork()).join();
        break;
      case "int64":
        EmptyMessage.encode(message.arrowTypeEnum.int64, writer.uint32(82).fork()).join();
        break;
      case "float16":
        EmptyMessage.encode(message.arrowTypeEnum.float16, writer.uint32(90).fork()).join();
        break;
      case "float32":
        EmptyMessage.encode(message.arrowTypeEnum.float32, writer.uint32(98).fork()).join();
        break;
      case "float64":
        EmptyMessage.encode(message.arrowTypeEnum.float64, writer.uint32(106).fork()).join();
        break;
      case "utf8":
        EmptyMessage.encode(message.arrowTypeEnum.utf8, writer.uint32(114).fork()).join();
        break;
      case "binary":
        EmptyMessage.encode(message.arrowTypeEnum.binary, writer.uint32(122).fork()).join();
        break;
      case "date32":
        EmptyMessage.encode(message.arrowTypeEnum.date32, writer.uint32(130).fork()).join();
        break;
      case "date64":
        EmptyMessage.encode(message.arrowTypeEnum.date64, writer.uint32(138).fork()).join();
        break;
      case "duration":
        writer.uint32(144).int32(message.arrowTypeEnum.duration);
        break;
      case "timestamp":
        Timestamp.encode(message.arrowTypeEnum.timestamp, writer.uint32(154).fork()).join();
        break;
      case "list":
        List.encode(message.arrowTypeEnum.list, writer.uint32(162).fork()).join();
        break;
      case "struct":
        Struct.encode(message.arrowTypeEnum.struct, writer.uint32(170).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ArrowType {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArrowType() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.arrowTypeEnum = { $case: "none", none: EmptyMessage.decode(reader, reader.uint32()) };
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.arrowTypeEnum = { $case: "bool", bool: EmptyMessage.decode(reader, reader.uint32()) };
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.arrowTypeEnum = { $case: "uint8", uint8: EmptyMessage.decode(reader, reader.uint32()) };
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.arrowTypeEnum = { $case: "int8", int8: EmptyMessage.decode(reader, reader.uint32()) };
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.arrowTypeEnum = { $case: "uint16", uint16: EmptyMessage.decode(reader, reader.uint32()) };
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.arrowTypeEnum = { $case: "int16", int16: EmptyMessage.decode(reader, reader.uint32()) };
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.arrowTypeEnum = { $case: "uint32", uint32: EmptyMessage.decode(reader, reader.uint32()) };
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.arrowTypeEnum = { $case: "int32", int32: EmptyMessage.decode(reader, reader.uint32()) };
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.arrowTypeEnum = { $case: "uint64", uint64: EmptyMessage.decode(reader, reader.uint32()) };
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.arrowTypeEnum = { $case: "int64", int64: EmptyMessage.decode(reader, reader.uint32()) };
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.arrowTypeEnum = { $case: "float16", float16: EmptyMessage.decode(reader, reader.uint32()) };
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.arrowTypeEnum = { $case: "float32", float32: EmptyMessage.decode(reader, reader.uint32()) };
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.arrowTypeEnum = { $case: "float64", float64: EmptyMessage.decode(reader, reader.uint32()) };
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.arrowTypeEnum = { $case: "utf8", utf8: EmptyMessage.decode(reader, reader.uint32()) };
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.arrowTypeEnum = { $case: "binary", binary: EmptyMessage.decode(reader, reader.uint32()) };
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.arrowTypeEnum = { $case: "date32", date32: EmptyMessage.decode(reader, reader.uint32()) };
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.arrowTypeEnum = { $case: "date64", date64: EmptyMessage.decode(reader, reader.uint32()) };
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.arrowTypeEnum = { $case: "duration", duration: reader.int32() as any };
          continue;
        }
        case 19: {
          if (tag !== 154) {
            break;
          }

          message.arrowTypeEnum = { $case: "timestamp", timestamp: Timestamp.decode(reader, reader.uint32()) };
          continue;
        }
        case 20: {
          if (tag !== 162) {
            break;
          }

          message.arrowTypeEnum = { $case: "list", list: List.decode(reader, reader.uint32()) };
          continue;
        }
        case 21: {
          if (tag !== 170) {
            break;
          }

          message.arrowTypeEnum = { $case: "struct", struct: Struct.decode(reader, reader.uint32()) };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ArrowType {
    return {
      $type: ArrowType.$type,
      arrowTypeEnum: isSet(object.none)
        ? { $case: "none", none: EmptyMessage.fromJSON(object.none) }
        : isSet(object.bool)
        ? { $case: "bool", bool: EmptyMessage.fromJSON(object.bool) }
        : isSet(object.uint8)
        ? { $case: "uint8", uint8: EmptyMessage.fromJSON(object.uint8) }
        : isSet(object.int8)
        ? { $case: "int8", int8: EmptyMessage.fromJSON(object.int8) }
        : isSet(object.uint16)
        ? { $case: "uint16", uint16: EmptyMessage.fromJSON(object.uint16) }
        : isSet(object.int16)
        ? { $case: "int16", int16: EmptyMessage.fromJSON(object.int16) }
        : isSet(object.uint32)
        ? { $case: "uint32", uint32: EmptyMessage.fromJSON(object.uint32) }
        : isSet(object.int32)
        ? { $case: "int32", int32: EmptyMessage.fromJSON(object.int32) }
        : isSet(object.uint64)
        ? { $case: "uint64", uint64: EmptyMessage.fromJSON(object.uint64) }
        : isSet(object.int64)
        ? { $case: "int64", int64: EmptyMessage.fromJSON(object.int64) }
        : isSet(object.float16)
        ? { $case: "float16", float16: EmptyMessage.fromJSON(object.float16) }
        : isSet(object.float32)
        ? { $case: "float32", float32: EmptyMessage.fromJSON(object.float32) }
        : isSet(object.float64)
        ? { $case: "float64", float64: EmptyMessage.fromJSON(object.float64) }
        : isSet(object.utf8)
        ? { $case: "utf8", utf8: EmptyMessage.fromJSON(object.utf8) }
        : isSet(object.binary)
        ? { $case: "binary", binary: EmptyMessage.fromJSON(object.binary) }
        : isSet(object.date32)
        ? { $case: "date32", date32: EmptyMessage.fromJSON(object.date32) }
        : isSet(object.date64)
        ? { $case: "date64", date64: EmptyMessage.fromJSON(object.date64) }
        : isSet(object.duration)
        ? { $case: "duration", duration: timeUnitFromJSON(object.duration) }
        : isSet(object.timestamp)
        ? { $case: "timestamp", timestamp: Timestamp.fromJSON(object.timestamp) }
        : isSet(object.list)
        ? { $case: "list", list: List.fromJSON(object.list) }
        : isSet(object.struct)
        ? { $case: "struct", struct: Struct.fromJSON(object.struct) }
        : undefined,
    };
  },

  toJSON(message: ArrowType): unknown {
    const obj: any = {};
    if (message.arrowTypeEnum?.$case === "none") {
      obj.none = EmptyMessage.toJSON(message.arrowTypeEnum.none);
    } else if (message.arrowTypeEnum?.$case === "bool") {
      obj.bool = EmptyMessage.toJSON(message.arrowTypeEnum.bool);
    } else if (message.arrowTypeEnum?.$case === "uint8") {
      obj.uint8 = EmptyMessage.toJSON(message.arrowTypeEnum.uint8);
    } else if (message.arrowTypeEnum?.$case === "int8") {
      obj.int8 = EmptyMessage.toJSON(message.arrowTypeEnum.int8);
    } else if (message.arrowTypeEnum?.$case === "uint16") {
      obj.uint16 = EmptyMessage.toJSON(message.arrowTypeEnum.uint16);
    } else if (message.arrowTypeEnum?.$case === "int16") {
      obj.int16 = EmptyMessage.toJSON(message.arrowTypeEnum.int16);
    } else if (message.arrowTypeEnum?.$case === "uint32") {
      obj.uint32 = EmptyMessage.toJSON(message.arrowTypeEnum.uint32);
    } else if (message.arrowTypeEnum?.$case === "int32") {
      obj.int32 = EmptyMessage.toJSON(message.arrowTypeEnum.int32);
    } else if (message.arrowTypeEnum?.$case === "uint64") {
      obj.uint64 = EmptyMessage.toJSON(message.arrowTypeEnum.uint64);
    } else if (message.arrowTypeEnum?.$case === "int64") {
      obj.int64 = EmptyMessage.toJSON(message.arrowTypeEnum.int64);
    } else if (message.arrowTypeEnum?.$case === "float16") {
      obj.float16 = EmptyMessage.toJSON(message.arrowTypeEnum.float16);
    } else if (message.arrowTypeEnum?.$case === "float32") {
      obj.float32 = EmptyMessage.toJSON(message.arrowTypeEnum.float32);
    } else if (message.arrowTypeEnum?.$case === "float64") {
      obj.float64 = EmptyMessage.toJSON(message.arrowTypeEnum.float64);
    } else if (message.arrowTypeEnum?.$case === "utf8") {
      obj.utf8 = EmptyMessage.toJSON(message.arrowTypeEnum.utf8);
    } else if (message.arrowTypeEnum?.$case === "binary") {
      obj.binary = EmptyMessage.toJSON(message.arrowTypeEnum.binary);
    } else if (message.arrowTypeEnum?.$case === "date32") {
      obj.date32 = EmptyMessage.toJSON(message.arrowTypeEnum.date32);
    } else if (message.arrowTypeEnum?.$case === "date64") {
      obj.date64 = EmptyMessage.toJSON(message.arrowTypeEnum.date64);
    } else if (message.arrowTypeEnum?.$case === "duration") {
      obj.duration = timeUnitToJSON(message.arrowTypeEnum.duration);
    } else if (message.arrowTypeEnum?.$case === "timestamp") {
      obj.timestamp = Timestamp.toJSON(message.arrowTypeEnum.timestamp);
    } else if (message.arrowTypeEnum?.$case === "list") {
      obj.list = List.toJSON(message.arrowTypeEnum.list);
    } else if (message.arrowTypeEnum?.$case === "struct") {
      obj.struct = Struct.toJSON(message.arrowTypeEnum.struct);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ArrowType>, I>>(base?: I): ArrowType {
    return ArrowType.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ArrowType>, I>>(object: I): ArrowType {
    const message = createBaseArrowType() as any;
    switch (object.arrowTypeEnum?.$case) {
      case "none": {
        if (object.arrowTypeEnum?.none !== undefined && object.arrowTypeEnum?.none !== null) {
          message.arrowTypeEnum = { $case: "none", none: EmptyMessage.fromPartial(object.arrowTypeEnum.none) };
        }
        break;
      }
      case "bool": {
        if (object.arrowTypeEnum?.bool !== undefined && object.arrowTypeEnum?.bool !== null) {
          message.arrowTypeEnum = { $case: "bool", bool: EmptyMessage.fromPartial(object.arrowTypeEnum.bool) };
        }
        break;
      }
      case "uint8": {
        if (object.arrowTypeEnum?.uint8 !== undefined && object.arrowTypeEnum?.uint8 !== null) {
          message.arrowTypeEnum = { $case: "uint8", uint8: EmptyMessage.fromPartial(object.arrowTypeEnum.uint8) };
        }
        break;
      }
      case "int8": {
        if (object.arrowTypeEnum?.int8 !== undefined && object.arrowTypeEnum?.int8 !== null) {
          message.arrowTypeEnum = { $case: "int8", int8: EmptyMessage.fromPartial(object.arrowTypeEnum.int8) };
        }
        break;
      }
      case "uint16": {
        if (object.arrowTypeEnum?.uint16 !== undefined && object.arrowTypeEnum?.uint16 !== null) {
          message.arrowTypeEnum = { $case: "uint16", uint16: EmptyMessage.fromPartial(object.arrowTypeEnum.uint16) };
        }
        break;
      }
      case "int16": {
        if (object.arrowTypeEnum?.int16 !== undefined && object.arrowTypeEnum?.int16 !== null) {
          message.arrowTypeEnum = { $case: "int16", int16: EmptyMessage.fromPartial(object.arrowTypeEnum.int16) };
        }
        break;
      }
      case "uint32": {
        if (object.arrowTypeEnum?.uint32 !== undefined && object.arrowTypeEnum?.uint32 !== null) {
          message.arrowTypeEnum = { $case: "uint32", uint32: EmptyMessage.fromPartial(object.arrowTypeEnum.uint32) };
        }
        break;
      }
      case "int32": {
        if (object.arrowTypeEnum?.int32 !== undefined && object.arrowTypeEnum?.int32 !== null) {
          message.arrowTypeEnum = { $case: "int32", int32: EmptyMessage.fromPartial(object.arrowTypeEnum.int32) };
        }
        break;
      }
      case "uint64": {
        if (object.arrowTypeEnum?.uint64 !== undefined && object.arrowTypeEnum?.uint64 !== null) {
          message.arrowTypeEnum = { $case: "uint64", uint64: EmptyMessage.fromPartial(object.arrowTypeEnum.uint64) };
        }
        break;
      }
      case "int64": {
        if (object.arrowTypeEnum?.int64 !== undefined && object.arrowTypeEnum?.int64 !== null) {
          message.arrowTypeEnum = { $case: "int64", int64: EmptyMessage.fromPartial(object.arrowTypeEnum.int64) };
        }
        break;
      }
      case "float16": {
        if (object.arrowTypeEnum?.float16 !== undefined && object.arrowTypeEnum?.float16 !== null) {
          message.arrowTypeEnum = { $case: "float16", float16: EmptyMessage.fromPartial(object.arrowTypeEnum.float16) };
        }
        break;
      }
      case "float32": {
        if (object.arrowTypeEnum?.float32 !== undefined && object.arrowTypeEnum?.float32 !== null) {
          message.arrowTypeEnum = { $case: "float32", float32: EmptyMessage.fromPartial(object.arrowTypeEnum.float32) };
        }
        break;
      }
      case "float64": {
        if (object.arrowTypeEnum?.float64 !== undefined && object.arrowTypeEnum?.float64 !== null) {
          message.arrowTypeEnum = { $case: "float64", float64: EmptyMessage.fromPartial(object.arrowTypeEnum.float64) };
        }
        break;
      }
      case "utf8": {
        if (object.arrowTypeEnum?.utf8 !== undefined && object.arrowTypeEnum?.utf8 !== null) {
          message.arrowTypeEnum = { $case: "utf8", utf8: EmptyMessage.fromPartial(object.arrowTypeEnum.utf8) };
        }
        break;
      }
      case "binary": {
        if (object.arrowTypeEnum?.binary !== undefined && object.arrowTypeEnum?.binary !== null) {
          message.arrowTypeEnum = { $case: "binary", binary: EmptyMessage.fromPartial(object.arrowTypeEnum.binary) };
        }
        break;
      }
      case "date32": {
        if (object.arrowTypeEnum?.date32 !== undefined && object.arrowTypeEnum?.date32 !== null) {
          message.arrowTypeEnum = { $case: "date32", date32: EmptyMessage.fromPartial(object.arrowTypeEnum.date32) };
        }
        break;
      }
      case "date64": {
        if (object.arrowTypeEnum?.date64 !== undefined && object.arrowTypeEnum?.date64 !== null) {
          message.arrowTypeEnum = { $case: "date64", date64: EmptyMessage.fromPartial(object.arrowTypeEnum.date64) };
        }
        break;
      }
      case "duration": {
        if (object.arrowTypeEnum?.duration !== undefined && object.arrowTypeEnum?.duration !== null) {
          message.arrowTypeEnum = { $case: "duration", duration: object.arrowTypeEnum.duration };
        }
        break;
      }
      case "timestamp": {
        if (object.arrowTypeEnum?.timestamp !== undefined && object.arrowTypeEnum?.timestamp !== null) {
          message.arrowTypeEnum = {
            $case: "timestamp",
            timestamp: Timestamp.fromPartial(object.arrowTypeEnum.timestamp),
          };
        }
        break;
      }
      case "list": {
        if (object.arrowTypeEnum?.list !== undefined && object.arrowTypeEnum?.list !== null) {
          message.arrowTypeEnum = { $case: "list", list: List.fromPartial(object.arrowTypeEnum.list) };
        }
        break;
      }
      case "struct": {
        if (object.arrowTypeEnum?.struct !== undefined && object.arrowTypeEnum?.struct !== null) {
          message.arrowTypeEnum = { $case: "struct", struct: Struct.fromPartial(object.arrowTypeEnum.struct) };
        }
        break;
      }
    }
    return message;
  },
};

messageTypeRegistry.set(ArrowType.$type, ArrowType);

function createBaseDatum(): Datum {
  return { $type: "wings.schema.Datum", type: undefined, content: new Uint8Array(0) };
}

export const Datum: MessageFns<Datum, "wings.schema.Datum"> = {
  $type: "wings.schema.Datum" as const,

  encode(message: Datum, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== undefined) {
      ArrowType.encode(message.type, writer.uint32(10).fork()).join();
    }
    if (message.content.length !== 0) {
      writer.uint32(18).bytes(message.content);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Datum {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDatum() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = ArrowType.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.content = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Datum {
    return {
      $type: Datum.$type,
      type: isSet(object.type) ? ArrowType.fromJSON(object.type) : undefined,
      content: isSet(object.content) ? bytesFromBase64(object.content) : new Uint8Array(0),
    };
  },

  toJSON(message: Datum): unknown {
    const obj: any = {};
    if (message.type !== undefined) {
      obj.type = ArrowType.toJSON(message.type);
    }
    if (message.content.length !== 0) {
      obj.content = base64FromBytes(message.content);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Datum>, I>>(base?: I): Datum {
    return Datum.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Datum>, I>>(object: I): Datum {
    const message = createBaseDatum() as any;
    message.type = (object.type !== undefined && object.type !== null) ? ArrowType.fromPartial(object.type) : undefined;
    message.content = object.content ?? new Uint8Array(0);
    return message;
  },
};

messageTypeRegistry.set(Datum.$type, Datum);

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { readonly $case: string }
    ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { readonly $case: T["$case"] }
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P> | "$type">]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
